import assert from 'node:assert/strict';
import fs from 'node:fs';

const classListSource = fs.readFileSync(new URL('./ClassListView.tsx', import.meta.url), 'utf8');
const appSource = fs.readFileSync(new URL('../App.tsx', import.meta.url), 'utf8');
const homeworkSource = fs.readFileSync(new URL('./HomeworkEntryView.tsx', import.meta.url), 'utf8');
const statusGroupSource = fs.readFileSync(new URL('../components/homework/HomeworkStatusButtonGroup.tsx', import.meta.url), 'utf8');

assert.match(classListSource, /onViewHomeworkEntry: \(classId: string\) => void;/, '班级列表应暴露作业录入回调。');
assert.match(classListSource, /label: '作业录入'/, '更多操作应展示作业录入入口。');
assert.match(classListSource, /activeActionPolicy\.canManuallyEnterHomework/, '作业录入入口应受任教班级权限控制。');
assert.match(classListSource, /runClassAction\(onViewHomeworkEntry\)/, '作业录入应携带当前班级。');
assert.match(classListSource, /title: '日常操作'/, '作业录入和兑换奖励应归入日常操作。');

assert.match(appSource, /currentView === 'homework_entry' && selectedClassId/, '应用应渲染作业录入页面。');
assert.match(appSource, /students=\{getMergedStudentsForClass\(selectedClassId\)\.filter/, '作业录入应读取当前班级学生。');
assert.match(appSource, /assignments=\{homeworkAssignments\}/, '班级作业录入应读取与图片识别共用的作业台账。');
assert.match(appSource, /onSyncAssignments=\{handleSyncRecognizedHomework\}/, '图片识别结果应同步写入共用作业台账。');
assert.match(appSource, /'homework_entry'[\s\S]*viewHandlesScroll/, '作业录入应使用页面内部滚动。');
assert.match(appSource, /createTeachingAssignments\(\['c_2025_1'\], '语文'\)[\s\S]*createTeachingAssignments\(\['c_2025_1'\], '书法'\)/, '演示账号应在同一班级配置多个任教科目。');
assert.match(appSource, /subject: '语文'[\s\S]*subject: '书法'/, '多科目状态应提供可切换的作业演示数据。');
assert.match(appSource, /title: '分数应用题'[\s\S]*source: 'ai_import'[\s\S]*title: '第二单元《秋天的雨》课文预习、生字词整理及课后习题第一至第三题订正'[\s\S]*dayOffset: -1/, '演示数据应覆盖识别来源、长主题和同日多次作业。');

assert.match(homeworkSource, /subjects: string\[\]/, '作业录入应由任教关系提供可选学科。');
assert.match(homeworkSource, /type HomeworkAssignment/, '手工录入应使用共享作业台账模型。');
assert.doesNotMatch(homeworkSource, /browseMode|作业查看方式|value: 'list'/, '作业录入不应增加无价值的列表模式。');
assert.match(homeworkSource, /<PillSelectionControl[\s\S]*value=\{subject\}[\s\S]*ariaLabel="任教学科"[\s\S]*semantics="tabs"/, '多个任教科目应通过报告同款标签切换。');
assert.doesNotMatch(homeworkSource, /activeAssignment\.source|>手工<|>识别</, '作业主题行不应展示无决策价值的录入来源标签。');
assert.match(homeworkSource, /setCalendarMonth\(current => addMonths\(current, -1\)\)/, '日历应支持查看上个月。');
assert.match(homeworkSource, /setCalendarMonth\(current => addMonths\(current, 1\)\)/, '日历应支持查看下个月。');
assert.match(homeworkSource, /assignmentsByDate\[dateText\]\?\.length/, '日历应标记每天的作业次数。');
assert.match(homeworkSource, /selectedDateAssignments/, '选择日期后应展示当天全部作业。');
assert.match(homeworkSource, /assignmentCount > 0[\s\S]*rounded-\[4px\][\s\S]*\{assignmentCount\}/, '有作业的日期应使用圆角矩形直接展示作业次数。');
assert.doesNotMatch(homeworkSource, /getDateMarkerTone|getAssignmentCompletionCount|tm-status-positive/, '日历次数不应再用颜色表达登记完成情况。');
assert.match(homeworkSource, />新增作业</, '日历卡片底部应只保留明确的新增作业入口。');
assert.match(homeworkSource, /selectedDateAssignments\.length > 0[\s\S]*space-y-\[var\(--tm-space-2\)\][\s\S]*selectedDateAssignments\.map\(assignment =>[\s\S]*rounded-\[var\(--tm-radius-card\)\][\s\S]*\[box-shadow:var\(--tm-shadow-card\)\]/, '当天每次作业都应使用一张独立卡片展示。');
assert.doesNotMatch(homeworkSource, /selectedDateAssignments\.map\(\(assignment, index\)[\s\S]*border-t/, '当天多次作业不应继续合并在一张卡片内用分隔线区分。');
assert.match(homeworkSource, /onClick=\{\(\) => startEdit\(assignment\)\}/, '点击任意作业记录应进入该次作业编辑。');
assert.match(homeworkSource, /<Pencil[\s\S]*aria-hidden="true"/, '作业记录行应使用编辑图标明确操作结果。');
assert.doesNotMatch(homeworkSource, /role="tab"|aria-selected=\{selected\}|activeAssignmentId/, '独立作业记录不应使用分类页签或选中态。');
assert.match(homeworkSource, /line-clamp-2[\s\S]*\{assignment\.title\}/, '较长的作业主题应支持两行展示。');
assert.doesNotMatch(homeworkSource, /activeAssignment\.title/, '日历卡片不应重复展示当前作业主题。');
assert.doesNotMatch(homeworkSource, /absolute bottom-\[calc\(var\(--tm-space-4\)/, '作业录入不应使用遮挡日历登记内容的悬浮新建按钮。');
assert.match(homeworkSource, /<MobileBottomSheet[\s\S]*title=\{editorMode === 'create' \? '新增作业' : '编辑作业'\}[\s\S]*size="full"/, '新增与编辑应复用公共近全屏底部弹窗。');
assert.match(homeworkSource, /open=\{editorMode !== null && Boolean\(draftAssignment\)\}/, '作业弹窗应由统一草稿状态控制。');
assert.match(homeworkSource, /footer=\{\([\s\S]*onClick=\{saveDraftAssignment\}[\s\S]*完成/, '弹窗底部应提供统一完成操作。');
assert.doesNotMatch(homeworkSource, /studentGroupSize|学生分组|第\{group\.label\}人|1-20|21-40|41-59/, '批量设置不应展示无意义的学生分段。');
assert.match(homeworkSource, /<HomeworkStatusButtonGroup/, '手工作业录入应复用共享五档等级控件。');
assert.match(statusGroupSource, /HOMEWORK_STATUS_VALUES\.map/, '共享等级控件应来自统一的五档业务枚举。');
assert.match(statusGroupSource, /size\?: 'default' \| 'compact'/, '共享等级控件应提供可见尺寸与触控尺寸分离的紧凑规格。');
assert.match(statusGroupSource, /size === 'compact'[\s\S]*h-9[\s\S]*rounded-\[8px\]/, '紧凑等级色块应保持36像素高度和8像素圆角。');
assert.match(homeworkSource, /ariaLabel="全班批量设置作业等级"[\s\S]*size="compact"/, '全班批量设置应使用紧凑等级色块。');
assert.match(homeworkSource, /ariaLabel=\{`设置\$\{result\.studentName\}作业等级`\} showAllTones \/>/, '学生逐行等级应继续使用默认可见高度。');
assert.match(homeworkSource, /showAllTones/, '批量与逐人登记都应直观展示五档语义颜色。');
assert.match(homeworkSource, /placeholder="输入作业主题"/, '作业弹窗应支持输入和编辑长主题。');
assert.match(homeworkSource, /批量设置[\s\S]*draftAssignment\.results\.map/, '作业弹窗应同时包含全班批量设置和连续学生名单。');
assert.match(homeworkSource, /result\.avatar \|\| ASSETS\.AVATAR\.GENERIC_BOY[\s\S]*getStudentNoSuffix\(result\.studentNo\)[\s\S]*result\.studentName/, '学生行应紧凑展示头像、学号后两位和姓名。');
assert.doesNotMatch(homeworkSource, /isCreating|draftTitle|createAssignment/, '主页面不应保留行内新建状态。');
assert.doesNotMatch(homeworkSource, /已录入 \{getAssignmentCompletionCount/, '页面顶部不应展示当前作业完成统计。');
assert.match(homeworkSource, /results: buildHomeworkResults\(students\)/, '新建作业应生成完整班级结果。');
assert.match(homeworkSource, /second\.date\.localeCompare\(first\.date\) \|\| second\.updatedAt/, '同日多次作业应作为独立记录排序展示。');
assert.match(homeworkSource, /const saveDraftAssignment[\s\S]*onSaveAssignment\(\{[\s\S]*\.\.\.draftAssignment/, '只有点击完成时才应把弹窗草稿写回共享台账。');
assert.match(homeworkSource, /const changeDraftResult[\s\S]*setDraftAssignment/, '逐人修改应先保存在当前弹窗草稿。');
assert.match(homeworkSource, /result\.status === status \? null : status/, '再次点选同一状态应恢复为未登记。');
assert.doesNotMatch(homeworkSource, /实时保存/, '弹窗草稿不应误导为实时写入台账。');
assert.doesNotMatch(homeworkSource, /学期|年级/, '手工作业录入不应要求维护学期或年级。');
assert.match(homeworkSource, /onClick=\{backAction\}/, '作业录入应使用页面顶部返回按钮。');
assert.match(homeworkSource, /--tm-border-subtle/, '作业录入普通边框应使用教师端浅边框 Token。');
assert.match(homeworkSource, /--tm-size-touch/, '作业录入触控区应使用教师端触控尺寸 Token。');
assert.doesNotMatch(homeworkSource, /(?:bg|text|border|shadow)-(?:blue|indigo|violet|cyan)-/, '作业录入不应残留旧蓝紫色。');
assert.doesNotMatch(homeworkSource, /#[0-9A-Fa-f]{3,8}|rgba\(/, '作业录入不应硬编码颜色。');
assert.doesNotMatch(homeworkSource, /保存作业录入/, '自动保存页面不应再放置保存按钮。');

console.log('ClassListView homework entry assertions passed');
