import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = relativePath => fs.readFileSync(new URL(relativePath, import.meta.url), 'utf8');
const typesSource = read('../types.ts');
const domainSource = read('../domain/studentCardDisplay.ts');
const groupDomainSource = read('../domain/groupCardDisplay.ts');
const evaluationDomainSource = read('../domain/evaluationCardDisplay.ts');
const appSource = read('../App.tsx');
const listSource = read('./ClassListView.tsx');
const detailSource = read('./ClassDetailView.tsx');
const rosterCardSource = read('../components/student/StudentRosterCard.tsx');
const evaluationSettingsSource = read('../components/student-performance/CardEvaluationDisplaySettings.tsx');
const performanceMetaSource = read('../components/student-performance/StudentPerformanceMeta.tsx');
const switchSource = read('../components/ui/MobileSettingsSwitchRow.tsx');
const segmentedControlSource = read('../components/ui/CompactSegmentedControl.tsx');
const tokenSource = read('../styles/teacherMobileTokens.ts');
const guidelinesSource = read('../../design-system/teacher-mobile/TEACHER_MOBILE_UI_GUIDELINES.md');

assert.match(typesSource, /studentCardDisplaySettings\?: StudentCardDisplaySettings/, '学生卡片显示设置应保存到班级信息。');
assert.match(typesSource, /groupCardDisplaySettings\?: GroupCardDisplaySettings/, '小组卡片显示设置应保存到班级信息。');
assert.match(typesSource, /showEvaluation: boolean/, '加扣分展示应使用独立总开关。');
assert.match(domainSource, /showLevel: true[\s\S]*DEFAULT_EVALUATION_CARD_DISPLAY_SETTINGS/, '未配置班级应默认展示等级。');
assert.match(evaluationDomainSource, /showEvaluation: true[\s\S]*showPraise: true[\s\S]*showCriticism: true[\s\S]*valueMode: 'count'/, '未配置班级与小组应默认展示全部加扣分次数。');
assert.match(groupDomainSource, /DEFAULT_EVALUATION_CARD_DISPLAY_SETTINGS/, '小组应复用公共加扣分展示默认配置。');
assert.match(evaluationDomainSource, /settings\?\.showPraise[\s\S]*settings\?\.showPraiseCount/, '旧版卡片加分开关应自动迁移。');
assert.match(evaluationDomainSource, /settings\?\.showEvaluation \?\? hasSelectedContent/, '旧版两项都关闭时应迁移为关闭总开关。');
assert.match(appSource, /handleUpdateStudentCardDisplaySettings/, '应用层应提供班级级学生卡片设置更新能力。');
assert.match(appSource, /studentCardDisplaySettings: settings/, '学生卡片设置应回写当前班级覆盖数据。');
assert.match(appSource, /groupCardDisplaySettings: settings/, '小组卡片设置应回写当前班级覆盖数据。');
assert.doesNotMatch(listSource, /学生卡片展示|小组卡片展示/, '班级卡片更多操作不应承载学生或小组展示配置。');
assert.match(detailSource, /aria-label="学生更多操作"/, '学生页应就近提供更多操作入口。');
assert.match(detailSource, /aria-label="小组更多操作"/, '分组页应就近提供更多操作入口。');
assert.match(detailSource, /open=\{Boolean\(moreActionTarget\)\}[\s\S]*title="更多操作"/, '学生与分组的外层操作抽屉应统一使用“更多操作”。');
assert.match(detailSource, /moreActionTarget === 'group' \? '小组卡片展示' : '学生卡片展示'/, '学生与分组操作菜单应展示对应的卡片设置入口。');
assert.match(detailSource, /title=\{cardDisplayTarget === 'group' \? '小组卡片展示' : '学生卡片展示'\}/, '卡片展示设置应使用独立公共底部弹窗。');
assert.match(detailSource, /label="显示等级"[\s\S]*<CardEvaluationDisplaySettings/, '学生设置应分开等级与评价数据。');
assert.match(evaluationSettingsSource, /label="显示加扣分"[\s\S]*checked=\{settings\.showEvaluation\}/, '加扣分设置应先提供独立总开关。');
assert.match(evaluationSettingsSource, /value: 'all', label: '全部'[\s\S]*value: 'praise', label: '加分'[\s\S]*value: 'criticism', label: '扣分'/, '开启后应通过三选一设置显示内容。');
assert.doesNotMatch(evaluationSettingsSource, /CheckIcon/, '加分和扣分的选中态不应重复展示勾选图标。');
assert.match(evaluationSettingsSource, /settings\.showEvaluation && \([\s\S]*显示内容[\s\S]*数值形式/, '只有开启总开关后才应显示内容和数值形式。');
assert.doesNotMatch(evaluationSettingsSource, /bg-\[var\(--tm-bg-surface-soft\)\]/, '加扣分设置不应继续使用大面积灰色容器。');
assert.equal((evaluationSettingsSource.match(/variant="settings"/g) ?? []).length, 2, '显示内容和数值形式应统一使用设置项分段控件。');
assert.match(evaluationSettingsSource, /value: 'count', label: '次数'[\s\S]*value: 'score', label: '分值'/, '次数和分值应使用互斥选择。');
assert.match(detailSource, /studentCardDisplaySettings\.showLevel && canConfigureLevelDisplay[\s\S]*统计范围/, '显示等级开启后应在等级组内渐进披露统计范围。');
assert.match(detailSource, /<CompactSegmentedControl[\s\S]*ariaLabel="等级统计范围"[\s\S]*semantics="group"/, '等级统计范围必须复用设计系统紧凑分段控件。');
assert.match(detailSource, /ariaLabel="等级统计范围"[\s\S]*variant="settings"/, '等级统计范围应使用与加扣分一致的设置项规格。');
assert.match(tokenSource, /--tm-selection-segment-settings-item-width': '72px'/, '设置控件应使用统一的单项宽度。');
assert.match(evaluationSettingsSource, /<div className="space-y-\[var\(--tm-space-2\)\]">[\s\S]*显示内容[\s\S]*数值形式/, '显示内容和数值形式之间应使用8像素间距。');
assert.match(switchSource, /role="switch"/, '通用设置行应提供开关语义。');
assert.match(switchSource, /surface\?: 'soft' \| 'plain'/, '通用设置开关行应支持无灰底的紧凑设置场景。');
assert.doesNotMatch(switchSource, /(?:^|\s)border(?:\s|\")/, '设置开关行不应使用实体边框。');
assert.doesNotMatch(switchSource, /focus-visible:ring/, '手机端设置开关聚焦时不应出现品牌红外环。');
assert.match(segmentedControlSource, /compact \? 'px-\[var\(--tm-selection-segment-compact-inset\)\] py-0'/, '紧凑分段控件的滑块应使用统一的四周内距。');
assert.match(tokenSource, /--tm-selection-segment-compact-active-radius'[\s\S]*--tm-selection-segment-compact-inset/, '紧凑分段控件的滑块圆角应根据轨道圆角和内距派生。');
assert.match(detailSource, /getStudentCardDisplaySettings\(classInfo\.studentCardDisplaySettings\)/, '学生页应读取当前班级的卡片显示设置。');
assert.match(detailSource, /getGroupCardDisplaySettings\(classInfo\.groupCardDisplaySettings\)/, '分组页应读取当前班级的小组卡片显示设置。');
assert.equal((detailSource.match(/displaySettings=\{studentCardDisplaySettings\}/g) ?? []).length, 3, '学生页、小组详情和新增学生卡片都应使用同一显示设置。');
assert.equal((detailSource.match(/showPraise=\{groupCardDisplaySettings\.showEvaluation && groupCardDisplaySettings\.showPraise\}/g) ?? []).length, 1, '小组加分显示设置应受总开关控制。');
assert.equal((detailSource.match(/showCriticism=\{groupCardDisplaySettings\.showEvaluation && groupCardDisplaySettings\.showCriticism\}/g) ?? []).length, 1, '小组扣分显示设置应受总开关控制。');
assert.match(detailSource, /valueMode=\{groupCardDisplaySettings\.valueMode\}/, '小组加分和扣分应共用同一次数或分值类型。');
assert.match(rosterCardSource, /displaySettings\.showLevel \? `等级分值/, '隐藏等级后读屏文案不应继续播报等级。');
assert.match(rosterCardSource, /displaySettings\.showEvaluation && displaySettings\.showPraise[\s\S]*displaySettings\.valueMode === 'score'[\s\S]*累计加分/, '加分读屏文案应受总开关控制并跟随次数或分值模式。');
assert.match(rosterCardSource, /displaySettings\.showEvaluation && displaySettings\.showCriticism[\s\S]*displaySettings\.valueMode === 'score'[\s\S]*累计扣分/, '扣分读屏文案应受总开关控制并跟随次数或分值模式。');
assert.match(performanceMetaSource, /valueMode === 'score' \? formatSignedScore\(summary\.praiseScore, '\+'\) : formatSignedCount/, '加分色片应根据共同类型切换次数或分值。');
assert.match(performanceMetaSource, /const formatSignedScore = \(score: number, sign: '\+' \| '-'\) => score === 0 \? '0' : `\$\{sign\}\$\{formatScore\(score\)\}`/, '学生卡片分值视觉文案不应重复显示“分”单位。');
assert.match(performanceMetaSource, /累计加分\$\{summary\.praiseScore\}分/, '学生卡片读屏文案应继续保留分值单位。');
assert.match(tokenSource, /'--tm-student-card-height-full': '120px'[\s\S]*'--tm-student-card-height-compact': '104px'[\s\S]*'--tm-student-card-height-minimal': '88px'/, '学生卡片三档高度应由教师手机端 Token 统一管理。');
assert.match(rosterCardSource, /visiblePerformanceRowCount === 2[\s\S]*--tm-student-card-height-full[\s\S]*--tm-student-card-height-compact[\s\S]*--tm-student-card-height-minimal/, '学生卡片应根据可见表现信息使用三档高度。');
assert.match(detailSource, /setMoreActionTarget\(null\);[\s\S]*setCardDisplayTarget\(target\);/, '打开设置前应先关闭操作菜单，避免弹窗叠加。');
assert.match(guidelinesSource, /学生页与分组页普通态工具栏的三点入口[\s\S]*设置按班级保存并默认全部开启/, '教师手机端规范应记录就近入口、默认值和保存范围。');

console.log('学生与小组卡片显示设置校验通过。');
