import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('./HomeworkBatchImportView.tsx', import.meta.url), 'utf8');
const recognitionSource = fs.readFileSync(new URL('../services/homeworkRecognitionService.ts', import.meta.url), 'utf8');
const statusGroupSource = fs.readFileSync(new URL('../components/homework/HomeworkStatusButtonGroup.tsx', import.meta.url), 'utf8');
const appSource = fs.readFileSync(new URL('../App.tsx', import.meta.url), 'utf8');
const detailSource = source.slice(source.indexOf('if (activeDraft)'), source.indexOf("renderHeader('作业录入', onBack)", source.indexOf('if (activeDraft)')));
const taskListSource = source.slice(source.indexOf('{drafts.map(draft =>'), source.indexOf('{drafts.length === 0'));

assert.match(source, /识别作业表/);
assert.match(source, /下载导入模版/);
assert.match(source, /renderHeader\('作业录入', onBack\)/, '页面标题应统一显示“作业录入”。');
assert.doesNotMatch(source, /renderHeader\('作业批量录入'/, '页面标题不应继续显示“作业批量录入”。');
assert.match(source, /<MobileEmptyState/, '无识别任务时应复用公共缺省态组件。');
assert.match(source, /ASSETS\.DEFAULT_STATE\.WORRIED_CLIPBOARD/, '无识别任务时应使用记录类统一缺省图。');
assert.doesNotMatch(source, /班级花名册|导入花名册/, '批量录入不应再展示独立花名册入口。');
assert.match(source, /capture="environment"/, '应支持手机后置摄像头拍照。');
assert.match(source, /type="file" accept="image\/\*" multiple/, '应支持从相册批量选择图片。');
assert.match(source, /maxImagesPerRecognition = 9/, '拍照和相册每次最多应提交9张图片。');
assert.match(source, /待识别图片/, '图片发送识别前应进入统一过渡页。');
assert.match(source, /继续拍照/, '拍照过渡页应支持多张连拍。');
assert.match(source, /开始识别（\{stagedImages\.length\}张）/, '多张图片应由用户确认后统一开始识别。');
assert.match(source, /stagedImages\.map\(image => image\.file\)/, '过渡页应把每张图片作为独立识别输入。');
assert.ok((source.match(/contentTone="plain"/g) ?? []).length >= 2, '识别作业表和下载导入模版弹窗内容区应使用页面底色 Token。');
assert.ok((source.match(/space-y-\[var\(--tm-space-(?:2|3)\)\] pt-\[var\(--tm-space-3\)\]/g) ?? []).length >= 2, '识别作业表和下载导入模版弹窗的第一张卡片应与标题栏保持标准间距。');
assert.doesNotMatch(source, /recognizeRosterFiles|onSaveRosterVersion/, '批量录入应复用现有班级学生数据。');
assert.match(source, /drafts\.map\(draft =>/, '识别任务应按图片生成独立卡片。');
assert.match(source, /draft\.previewUrl[\s\S]*draft\.className[\s\S]*draft\.subject[\s\S]*draft\.assignments\.length/, '图片卡片应展示原图缩略图、班级、学科和作业次数。');
assert.match(source, /\$\{issueCount\}项待核对[\s\S]*已录入/, '图片卡片应区分待核对和已录入状态。');
assert.match(source, /openDraft[\s\S]*setReviewMode\(hasIssues \? 'issues' : 'all'\)/, '有异常应默认查看待核对项，无异常应直接查看完整结果。');
assert.match(source, /ariaLabel="识别结果查看范围"/, '有异常时应支持在待核对和完整结果之间切换。');
assert.match(source, /reviewTabsVisible/, '进入过待核对的任务应保持页签稳定。');
assert.match(source, /已完成核对/, '最后一项处理完成后应在原页展示完成状态。');
assert.doesNotMatch(detailSource, /\{unresolvedIssues\.length > 0 \? `\$\{unresolvedIssues\.length\}项待核对`/, '识别详情顶部不应重复展示待核对数量。');
assert.match(source, /aria-label="选择班级"/, '错班图片必须人工匹配现有班级。');
assert.match(source, /aria-label="选择学生"/, '无法匹配的学号应在异常项中人工匹配学生。');
assert.match(source, /matchDraftStudent/, '学生匹配应直接更新当前识别草稿。');
assert.match(source, /进入补全/, '缺少元数据时应进入单次作业结果补全。');
assert.match(source, /保留原记录/, '冲突时默认保留已有记录。');
assert.match(source, /aria-label="修改班级"/, '完整结果应允许修改班级。');
assert.match(source, /title="确认更换班级"/, '更换班级前必须二次确认。');
assert.match(source, /重新匹配所有学生/, '更换班级应明确说明重新匹配影响。');
assert.match(source, /hasRematchIssues[\s\S]*setReviewTabsVisible\(true\)[\s\S]*setReviewMode\('issues'\)/, '换班重新匹配产生异常时应恢复待核对入口。');
assert.match(source, /aria-label="修改学科"/, '完整结果应允许修改学科。');
assert.match(source, /setActiveAssignmentDetailId\(assignment\.id\)/, '批次中的单次作业应进入独立结果子页面。');
assert.match(source, /renderHeader\('作业结果',[\s\S]*setActiveAssignmentDetailId\(null\)/, '作业结果子页面应可返回当前图片详情。');
assert.doesNotMatch(source, /expandedAssignmentId|setExpandedAssignmentId/, '批次详情不应继续内嵌展开长名单。');
assert.match(source, /aria-label="作业日期"[\s\S]*aria-label="作业主题"[\s\S]*aria-label="学生作业结果"/, '作业结果子页面应允许修改日期、主题和学生等级。');
assert.match(source, /grid-cols-\[104px_minmax\(0,1fr\)\][\s\S]*resultItem\.avatar[\s\S]*getStudentNoSuffix\(resultItem\.studentNo\)[\s\S]*resultItem\.studentName[\s\S]*HomeworkStatusButtonGroup/, '学生头像、短学号、姓名和作业等级应紧凑展示在同一行。');
assert.match(source, /<HomeworkStatusButtonGroup/, '识别核对与完整结果应使用共享五档等级控件。');
assert.match(statusGroupSource, /tm-chart-positive[\s\S]*tm-chart-data-default[\s\S]*tm-chart-warning[\s\S]*tm-brand-primary[\s\S]*tm-text-secondary/, '五档等级应依次使用报告绿、报告蓝、报告警示色、品牌红和中性灰。');
assert.equal((statusGroupSource.match(/selected: 'border-0[^']*text-\[var\(--tm-text-inverse\)\]'/g) ?? []).length, 5, '五档选中态都应为无边框实色白字。');
assert.match(source, /onSubmitAssignments\(draftsWithPreviews\.flatMap\(draft => draft\.assignments\)\)/, '识别完成后应把多图结果一次合并写入作业台账。');
assert.match(source, /onSyncAssignments/, '核对和修改识别结果后应实时同步作业台账。');
assert.doesNotMatch(source, /submitDraft|确认录入|统一提交/, '识别结果不应再要求人工确认录入。');
assert.match(source, /onDeleteTask\(deleteDraft\)/, '确认删除后应调用识别任务删除能力。');
assert.match(source, /title="删除识别任务"/, '识别任务应使用删除确认抽屉。');
assert.doesNotMatch(taskListSource, /<ChevronRight/, '识别任务卡片不应展示多余的右箭头。');
assert.match(taskListSource, /更多操作[\s\S]*<MoreHorizontal/, '识别任务卡片应使用三点菜单承载低频操作。');
assert.match(source, /title="识别任务操作"[\s\S]*删除识别任务/, '点击三点菜单后才应展示删除识别任务。');
assert.match(source, /同时撤销[\s\S]*本次识别产生的/, '删除任务必须明确会同步撤销关联作业。');
assert.match(source, /tasks: drafts[\s\S]*onChangeTasks: setDrafts/, '识别任务应由页面外层保存，离开后仍可继续核对。');
assert.match(appSource, /homeworkImportTasks[\s\S]*handleSyncRecognizedHomework[\s\S]*handleDeleteHomeworkImportTask/, '应用层应统一维护识别任务、作业同步和删除。');
assert.match(appSource, /setHomeworkAssignments\(current => current\.filter\(assignment => !assignmentIds\.has\(assignment\.id\)\)\)/, '删除识别任务时应同步撤销对应作业。');
assert.match(source, /issueCount > 0 \? `\$\{issueCount\}项待核对` : '已录入'/, '无异常任务应直接展示已录入状态。');
assert.doesNotMatch(source, /ariaLabel="模板纸张"/, '固定的A4、A3模板不应再要求先切换规格。');
assert.match(source, /下载 \{pageSize\} 模版/, '每份模版应提供独立下载按钮。');
assert.match(source, /downloadPrintTemplate\(pageSize\)/, '模板卡片应直接下载自身规格。');
assert.match(source, /预览\$\{pageSize\}模板/, '每份模板应提供独立预览入口。');
assert.match(source, /getHomeworkTemplatePreviewDataUrl/, '模板缩略图必须来自实际模板画布。');
assert.match(source, /\{templatePreviewPageSize\} 模版预览/, '模版应支持大图预览。');
assert.match(source, /templatePreviewZoomed/, '大图预览应支持放大查看。');
assert.doesNotMatch(source, /保存图片|打印\/PDF|分享模板/, '模板抽屉不应恢复旧的并列导出操作。');
assert.match(source, /A4: '学号01—72'/);
assert.match(source, /A3: '学号001—100'/);
assert.match(source, /printHomeworkTemplate\(\{ pageSize \}\)/, '模板导出不应再依赖预选规格。');
assert.doesNotMatch(source, /学期|独立年级/, '批量录入页面不应要求维护学期或独立年级。');
assert.doesNotMatch(source, /aria-label="任课教师"/, '批量识别不应要求补充任课教师。');

assert.match(recognitionSource, /raw\.assignments\.slice\(0, 6\)/, '一张作业表最多生成6次作业。');
assert.match(recognitionSource, /fileIndex === 0 && studentIndex === 3/, '演示数据应同时覆盖待核对和无异常图片。');
assert.match(recognitionSource, /空白必须返回空字符串，绝不能把空白判断为X/, '识别提示必须明确空白规则。');
assert.match(recognitionSource, /getHomeworkStatusFromCode\(rawResult\.code\)/, '等级码应统一映射业务值。');
assert.match(recognitionSource, /classSequence/, '通用模板应通过纸面学号识别学生行。');
assert.match(recognitionSource, /rosterBySequence/, '识别结果应以纸面学号映射现有班级学生。');
assert.match(recognitionSource, /纸面学号/, '识别协议应将印刷序号统一称为学号。');
assert.match(recognitionSource, /不识别或推测姓名、完整学生编号/, '作业表识别不得依赖纸面姓名或完整学生编号。');
assert.doesNotMatch(recognitionSource, /recognizeRosterFiles/, '批量识别服务不应再提供独立花名册导入。');
assert.doesNotMatch(recognitionSource, /"teacherName":"任课教师"/, '识别协议不应包含任课教师。');
assert.match(recognitionSource, /作业等级需要核对/, '低置信度异常应使用老师能理解的业务文案。');
assert.doesNotMatch(recognitionSource, /的等级码需要核对/, '界面异常文案不应使用等级码术语。');

console.log('Homework batch import assertions passed');
