import assert from 'node:assert/strict';
import fs from 'node:fs';

const appSource = fs.readFileSync(new URL('../App.tsx', import.meta.url), 'utf8');
const classListSource = fs.readFileSync(new URL('./ClassListView.tsx', import.meta.url), 'utf8');
const recordSource = fs.readFileSync(new URL('./ClassRecordLogView.tsx', import.meta.url), 'utf8');
const inputSource = fs.readFileSync(new URL('./RecordInputView.tsx', import.meta.url), 'utf8');
const detailSource = fs.readFileSync(new URL('./student-team/StudentTeamDetailView.tsx', import.meta.url), 'utf8');
const editorSource = fs.readFileSync(new URL('./student-team/StudentTeamEditorView.tsx', import.meta.url), 'utf8');
const createSource = fs.readFileSync(new URL('./student-team/StudentTeamCreateView.tsx', import.meta.url), 'utf8');
const managementActionsSource = fs.readFileSync(new URL('./student-team/StudentTeamManagementActions.tsx', import.meta.url), 'utf8');
const radioOptionSource = fs.readFileSync(new URL('../components/ui/MobileRadioOptionCard.tsx', import.meta.url), 'utf8');
const compactStudentSource = fs.readFileSync(new URL('../components/student/StudentCompactSelectItem.tsx', import.meta.url), 'utf8');
const typeSource = fs.readFileSync(new URL('../types.ts', import.meta.url), 'utf8');

const requireText = (source, needle, message) => {
  assert.ok(source.includes(needle), message);
};

requireText(classListSource, "value: 'class'", '班级页必须保留老师可理解的“班级”页签。');
requireText(classListSource, "label: '班级'", '班级页签必须展示“班级”文案。');
requireText(classListSource, "value: 'team'", '班级页必须提供“社团与团队”页签。');
requireText(classListSource, "label: '社团与团队'", '团队页签必须展示“社团与团队”文案。');
requireText(classListSource, '<MobileSlidingSegmentedControl', '班级与社团页签必须使用公共滑块控件。');
assert.ok(!classListSource.includes('ClassSourceTrigger'), '班级页顶部不得继续提供来源切换。');
requireText(classListSource, 'h-[var(--mini-program-title-bar-height,44px)] items-center [padding-right:var(--mini-program-capsule-right-inset,0px)]', '班级与社团页签必须和微信原生胶囊处于同一标题栏。');
requireText(classListSource, "activeListTab: 'class' | 'team';", '班级页签必须由导航层持有，返回团队列表时不得重置。');
requireText(appSource, "const [classListTab, setClassListTab]", 'App 必须保存班级页签状态。');
requireText(classListSource, "activeListTab === 'team' && (", '社团与团队页签必须挂载独立列表区域。');
requireText(classListSource, 'visibleStudentTeams.map(renderStudentTeamCard)', '社团与团队页签必须展示权限过滤后的团队列表。');
requireText(classListSource, 'showParticipatingTeamsOnly', '管理人员必须能用轻量勾选框筛选自己参与的团队。');
requireText(classListSource, '我参与的', '团队筛选文案必须符合老师认知。');
requireText(classListSource, 'isSchoolManager', '普通老师不应展示无意义的参与团队筛选。');
requireText(typeSource, 'export interface SchoolStudentTeam', '学校社团与团队必须使用独立领域模型。');
requireText(typeSource, "status: 'active' | 'archived';", '解散团队必须采用归档状态，保留历史评价。');
requireText(typeSource, "visibility: 'collaborators' | 'management';", '团队必须保存老师主动选择的可见范围。');
requireText(typeSource, 'ownerId: string;', '团队必须使用稳定教师编号判断创建人。');
requireText(typeSource, 'collaboratorIds: string[];', '团队必须保存受邀协作老师。');

requireText(editorSource, 'classes: ClassInfo[];', '创建团队必须接收学校内多个班级。');
requireText(editorSource, 'const [selectedIds, setSelectedIds]', '跨班切换时必须保留已选成员。');
requireText(editorSource, 'activeStudents.forEach(student =>', '成员选择必须支持按班全选。');
requireText(editorSource, "allActiveSelected ? '取消全选' : '全选'", '团队选人应统一使用“全选 / 取消全选”文案。');
assert.ok(!editorSource.includes('全选本班') && !editorSource.includes('取消全班'), '团队选人不应使用局限于本班的旧文案。');
requireText(editorSource, '谁可以看到', '创建团队必须要求老师选择可见范围。');
requireText(editorSource, "tag: '私密'", '私密范围必须使用“私密”标签表达。');
requireText(editorSource, '重点关注的学生单独圈出', '私密范围应说明适合重点关注学生的使用场景。');
requireText(editorSource, "tag: '公开'", '公开范围必须使用“公开”标签表达。');
requireText(editorSource, '学校社团或跨班团队', '公开范围应说明适合学校社团或跨班团队。');
requireText(editorSource, '减少重复建立', '公开范围应说明公开后可减少重复建立。');
requireText(editorSource, 'MobileRadioOptionCard', '团队可见范围应使用通用单选配置卡片。');
requireText(classListSource, "import StudentTeamCreateView from './student-team/StudentTeamCreateView';", '新建社团或团队应使用独立页面视图。');
requireText(classListSource, 'const [teamCreateOpen, setTeamCreateOpen]', '新建社团或团队页面需要独立的页面状态。');
requireText(classListSource, 'if (mode === \'create\')', '新建入口应与团队设置、调整学生的弹窗入口分离。');
requireText(classListSource, '<StudentTeamCreateView', '新建社团或团队应渲染页面级创建视图。');
requireText(createSource, '完成（${selectedIds.size}人）', '创建页面底部主按钮应展示已选人数。');
requireText(createSource, '<MobileClassPickerSheet', '创建页面的班级筛选应复用公共班级选择弹窗。');
requireText(createSource, 'commitMode="immediate"', '创建页面的班级单选应即时提交并关闭公共选择弹窗。');
requireText(createSource, 'focus:border-[var(--tm-input-focus-border)] focus:ring-2 focus:ring-[var(--tm-input-focus-ring)]', '新建团队名称输入框必须使用统一的输入聚焦 Token。');
requireText(createSource, 'bg-[var(--tm-bg-surface-glass)] px-[var(--tm-space-5)] pb-[calc(var(--tm-space-4)+env(safe-area-inset-bottom))]', '创建页底部主操作区必须使用公共玻璃表面和安全区 Token。');
requireText(createSource, 'min-h-[52px] w-full', '创建页底部主按钮必须满足统一的触控高度。');
requireText(createSource, 'sticky top-0 z-30 bg-[var(--tm-bg-surface)]', '创建页选人工具栏必须高于滚动中的学生卡片。');
assert.ok(!createSource.includes('已选 {selectedIds.size} 人'), '创建页面不应在顶部重复展示已选人数。');
assert.ok(!editorSource.includes('已选 {selectedIds.size} 人'), '调整学生弹窗不应在顶部重复展示已选人数。');
requireText(editorSource, '<MobileClassCascadePicker', '学生选择中的班级筛选应复用公共级联选择内容。');
assert.ok(!editorSource.includes('MobileClassPickerSheet'), '学生选择弹窗内不得再嵌套公共班级底部弹窗。');
requireText(editorSource, "type MemberPickerView = 'students' | 'classes';", '班级筛选应在同一个学生选择弹窗内切换视图。');
requireText(editorSource, 'bg-[var(--tm-bg-surface)] px-3 py-2', '团队选人工具栏应沿用学生选择器的白色工具栏样式。');
requireText(editorSource, 'sticky top-0 z-30 -mx-3 bg-[var(--tm-bg-surface)] px-3 py-2', '团队选人工具栏必须高于滚动中的学生卡片。');
requireText(createSource, 'data-teacher-demo-context="student-team-other-search"', '其他班级精确搜索状态应向手机壳提供演示标注上下文。');
assert.ok(!createSource.includes('bg-[var(--tm-bg-surface-soft)] pt-[var(--tm-space-2)]'), '其他班级搜索栏与来源页签之间不得保留浅灰空隙。');
assert.ok(!editorSource.includes('bg-[var(--tm-bg-surface-soft)] pt-[var(--tm-space-2)]'), '调整成员弹窗的其他班级搜索栏与来源页签之间不得保留浅灰空隙。');
requireText(editorSource, 'onToggle={toggleStudent} className="pt-2"', '团队学生网格应在浅灰内容层顶部保留8像素安全留白。');
requireText(compactStudentSource, 'relative isolate flex min-w-0', '学生选择卡片必须建立独立层叠范围，避免选中角标穿过吸顶工具栏。');
requireText(compactStudentSource, 'secondaryLabel?: string;', '公共学生选择卡片应支持展示班级副标题。');
requireText(compactStudentSource, 'showRosterNumber?: boolean;', '公共学生选择卡片应支持跨班搜索时隐藏学号。');
requireText(createSource, "sections={[{ id: 'other-class-search', students: exactSearchResults }]}", '新建页的跨班搜索结果必须复用公共学生卡片网格。');
requireText(editorSource, "sections={[{ id: 'other-class-search', students: exactSearchResults }]}", '调整学生弹窗的跨班搜索结果必须复用公共学生卡片网格。');
requireText(createSource, 'getSecondaryLabel={student => (student as StudentTeamSearchResult).classLabel}', '新建页搜索卡片必须展示规范化班级名。');
requireText(editorSource, 'getSecondaryLabel={student => (student as StudentTeamSearchResult).classLabel}', '调整学生弹窗搜索卡片必须展示规范化班级名。');
requireText(appSource, 'getTeacherClassDisplayName(classInfo, activeTeacherSpace)', '跨班搜索结果必须按当前学校空间格式化班级名。');
requireText(appSource, 'gender: student.gender,', '跨班搜索结果应提供公共学生卡片所需的性别头像回退信息。');
requireText(appSource, 'avatar: student.avatar,', '跨班搜索结果应沿用学生已有头像。');
requireText(editorSource, "useState<SchoolStudentTeam['visibility'] | null>", '新建团队的可见范围不得预设默认值。');
assert.ok(!editorSource.includes('showDiscardConfirm') && !editorSource.includes('放弃新建社团或团队'), '新建社团或团队点击关闭不应再触发二次确认。');
requireText(radioOptionSource, 'aria-describedby', '单选配置卡片必须关联场景说明。');
requireText(radioOptionSource, 'role="radio"', '单选配置卡片必须提供单选语义。');
requireText(radioOptionSource, 'tag?: string;', '单选配置卡片必须支持独立的范围标签。');
requireText(radioOptionSource, "tagTone?: 'neutral' | 'red' | 'orange' | 'jade' | 'gold';", '单选配置卡片标签必须支持班级页同类的彩色语义。');
requireText(radioOptionSource, 'aria-labelledby={tag ? `${id}-tag ${id}-title` : `${id}-title`}', '单选配置卡片的读屏名称必须包含范围标签。');
requireText(radioOptionSource, 'border-[var(--tm-selection-card-selected-border)]', '单选卡片选中态应使用品牌色边框 Token。');
requireText(radioOptionSource, 'bg-[var(--tm-selection-card-bg)]', '单选卡片应使用白色表面 Token 与班级页卡片保持一致。');
assert.ok(!radioOptionSource.includes('bg-[var(--tm-brand-primary-soft)] text-[var(--tm-brand-primary)]'), '单选卡片选中态不得使用整卡浅红填充。');
requireText(editorSource, 'tagTone: \'red\'', '私密标签应使用班级页同类的红色浅底标签。');
requireText(editorSource, 'tagTone: \'jade\'', '公开标签应使用班级页同类的青绿色浅底标签。');
assert.ok(!editorSource.includes('选择后，符合范围的老师才能查看和评价这个团队'), '可见范围区域不得保留重复的权限解释文案。');
requireText(editorSource, "export type StudentTeamEditorMode = 'create' | 'settings' | 'members';", '创建、团队设置与调整学生必须使用明确的渐进流程模式。');
requireText(editorSource, 'open: boolean;', '团队编辑器必须作为公共弹窗挂载，不得继续作为独立页面。');
requireText(editorSource, '<MobileBottomSheet', '创建团队必须复用公共底部弹窗。');
requireText(createSource, "type CreatePage = 'details' | 'members';", '新建团队页面必须采用基础信息到成员选择的两步流程。');
requireText(editorSource, "setPage('members')", '基础信息完成后必须在当前弹窗进入学生选择。');
requireText(editorSource, "? '选择学生'", '创建首屏必须只保留进入学生选择的唯一主操作。');
requireText(editorSource, '`完成（${selectedIds.size}人）`', '第二步主操作必须明确展示已选人数。');
requireText(editorSource, 'placeholder="例如：篮球社"', '名称示例必须与新建分组统一使用中文冒号。');
requireText(editorSource, "type MemberScope = 'authorized' | 'other';", '学生选择必须通过来源 Tab 区分有权限班级和其他班级。');
requireText(editorSource, "{ value: 'authorized', label: '我的班级' }", '学生来源 Tab 必须使用教师熟悉的我的班级文案。');
requireText(editorSource, "{ value: 'other', label: '其他班级' }", '学生来源 Tab 必须明确标识其他班级。');
requireText(editorSource, '<CompactSegmentedControl', '学生来源切换必须复用公共分段控件。');
assert.ok(!editorSource.includes('open={showOtherStudents}'), '跨班精确查找不得叠加第二层底部弹窗。');
requireText(editorSource, '输入完整姓名', '无权限班级学生只能通过完整姓名精确查找。');
requireText(editorSource, 'searchStudentsByExactName', '跨班学生检索必须由受控精确搜索回调提供结果。');
requireText(editorSource, 'setExactSearchResults(normalizedName ? searchStudentsByExactName(normalizedName) : [])', '跨班学生检索必须只提交完整姓名并按精确结果展示。');
requireText(editorSource, 'fillTone="soft"', '有权限和其他班级搜索框都必须使用统一的浅色底。');
assert.ok(!editorSource.includes('搜索姓名或学号'), '跨班成员检索不得使用学号。');
assert.ok(!editorSource.includes('类型'), '创建团队不得要求老师理解或选择团队类型。');
requireText(appSource, 'const activeSpaceStudents = activeSpaceClasses.flatMap', '全局精确检索必须以当前学校空间的学生索引为数据源。');
requireText(appSource, "student.name.trim().replace(/\\s+/g, '') === normalizedQuery", '全局检索必须按完整姓名精确匹配，不得使用前缀或模糊匹配。');
requireText(appSource, 'id: student.id,', '跨班检索结果必须返回稳定学生编号。');
requireText(appSource, 'grade: student.grade,', '跨班检索结果必须返回年级用于同名消歧。');
requireText(appSource, 'class: student.class,', '跨班检索结果必须返回班级用于同名消歧。');
const exactSearchSource = appSource.slice(appSource.indexOf('const searchStudentsByExactName'), appSource.indexOf('const activeTeacherClassIds'));
assert.ok(!exactSearchSource.includes('studentNo'), '跨班检索结果不得返回学号。');

assert.ok(!detailSource.includes('contextLabel={student.class}'), '团队成员卡不得展示原班级。');
requireText(detailSource, "from '../../components/student/StudentRosterCard'", '团队成员页必须复用班级花名册学生卡。');
requireText(detailSource, '全选', '团队成员页必须沿用班级列表的多选工具。');
requireText(detailSource, '反选', '团队成员页必须沿用班级列表的反选工具。');
requireText(detailSource, '学生卡片展示', '团队成员页必须沿用学生卡片展示设置。');
requireText(managementActionsSource, '调整学生', '创建人的成员维护必须使用独立入口。');
requireText(managementActionsSource, '团队设置', '创建人的基础信息维护必须使用独立入口。');
assert.ok(!detailSource.includes('编辑名称与成员'), '团队更多操作不得继续进入混合编辑长页面。');
requireText(managementActionsSource, '邀请协作老师', '只有创建人应获得协作评价邀请入口。');
requireText(detailSource, '<MenuIcon className="h-5 w-5" />', '团队详情更多操作必须放在多选旁边并复用班级工具栏图标。');
assert.ok(!detailSource.includes('MoreHorizontal'), '团队详情标题栏不得放置另一套更多操作。');
requireText(classListSource, 'aria-label={`${team.name}更多操作`}', '团队卡片必须使用独立的三点更多入口。');
requireText(classListSource, '<WechatMoreIcon className="h-5 w-5" />', '团队卡片必须与班级卡片复用微信三点图标。');
requireText(appSource, 'canManageSelectedStudentTeam', '团队编辑、邀请和解散必须按创建人权限控制。');
requireText(appSource, 'onUpdate={handleUpdateStudentTeam}', '团队设置与调整学生必须在当前页面弹窗内保存。');
assert.ok(!appSource.includes("'student_team_editor'"), '团队创建与维护不得保留独立页面路由。');
requireText(appSource, "isSchoolManager && team.visibility === 'management'", '管理人员只能看到明确向管理人员公开的团队。');
requireText(appSource, "const selectedStudentTeamCandidateIds = selectedStudentTeamStudents.map(student => student.id);", '团队录入候选范围必须等于当前有效成员。');
requireText(appSource, "currentView === 'student_team_detail' ? selectedStudentTeamCandidateIds : []", '只有团队成员页录入时才应注入团队候选范围。');
requireText(inputSource, 'candidateStudentIds?: string[];', '原有录入控件必须接收候选成员编号。');
requireText(inputSource, 'candidateStudentIds,', '语音、拍照和文字提交必须原样回传候选成员编号。');
requireText(appSource, "setCurrentView('student_team_detail');", '团队录入完成后必须回到团队成员页。');

assert.ok(!recordSource.includes('社团与团队'), '记录页不得增加社团与团队入口。');
assert.ok(!recordSource.includes('candidateStudentIds'), '记录页展示流程不得承担团队候选范围识别。');

const featureSources = [appSource, classListSource, detailSource, editorSource, managementActionsSource].join('\n');
for (const forbiddenCopy of ['特殊群体', '群组类型', '可评价学生名单', '行政班']) {
  assert.ok(!featureSources.includes(forbiddenCopy), `页面不得出现“${forbiddenCopy}”。`);
}

console.log('Student team flow assertions passed');
