export const teacherBrandPalette = {
  red: {
    50: '#FFF1F1',
    100: '#FFE2E2',
    200: '#FFC7C7',
    300: '#F99A98',
    400: '#EE615F',
    500: '#E02727',
    600: '#CC2020',
    700: '#BA352E',
    800: '#92221F',
    900: '#731B1A',
  },
  orange: {
    50: '#FFF5EC',
    100: '#FFE8D4',
    200: '#FFD0A5',
    300: '#FFB56F',
    400: '#FF8B33',
    500: '#F75C03',
    600: '#D94E00',
    700: '#B83F00',
    800: '#913406',
    900: '#762D0B',
  },
  gold: {
    50: '#FFF8E5',
    100: '#FFEFC2',
    200: '#FFE294',
    300: '#FFD56A',
    400: '#FDB63A',
    500: '#FA9C00',
    600: '#C88100',
    700: '#9A5B00',
    800: '#7A4900',
    900: '#5C3800',
  },
  jade: {
    50: '#ECF8F6',
    100: '#D4EEE9',
    200: '#ADDCD4',
    300: '#79C3B7',
    400: '#2CCBA3',
    500: '#278779',
    600: '#1C7167',
    700: '#155B54',
    800: '#124943',
    900: '#103D38',
  },
  neutral: {
    0: '#FFFFFF',
    25: '#FFFCFA',
    50: '#F8F6F5',
    100: '#F1EEEC',
    200: '#E7E2DF',
    300: '#D2CBC7',
    400: '#A49C97',
    450: '#918985',
    500: '#6D6764',
    550: '#7B7572',
    700: '#403C3A',
    900: '#171513',
  },
  // 深薄荷：仅用于五育-美育分类，与玉石青受众色、体育绿区分。
  mint: {
    500: '#14A085',
  },
  green: {
    50: '#F4FBF4',
    100: '#D4EAD5',
    500: '#48A04D',
    700: '#2E7D32',
  },
  rose: {
    50: '#FFF6F5',
    100: '#F0D7D4',
    500: '#AB352C',
    700: '#AB352C',
  },
} as const;

export const teacherBrandSemantic = {
  primary: teacherBrandPalette.red[500],
  primaryStrong: teacherBrandPalette.red[700],
  primaryHover: teacherBrandPalette.red[600],
  primaryPressed: teacherBrandPalette.red[700],
  primarySoft: teacherBrandPalette.red[50],
  primarySoftStrong: teacherBrandPalette.red[100],
  secondary: teacherBrandPalette.orange[500],
  secondaryStrong: teacherBrandPalette.orange[700],
  secondarySoft: teacherBrandPalette.orange[50],
  reward: teacherBrandPalette.gold[500],
  rewardStrong: teacherBrandPalette.gold[700],
  rewardSoft: teacherBrandPalette.gold[50],
  positive: teacherBrandPalette.green[500],
  positiveStrong: teacherBrandPalette.green[700],
  positiveSoft: teacherBrandPalette.green[50],
  negative: teacherBrandPalette.rose[500],
  negativeStrong: teacherBrandPalette.rose[700],
  negativeSoft: teacherBrandPalette.rose[50],
  page: '#FFF9F6',
  pageMid: '#FFFDFB',
  pageLow: '#FFF7F3',
  surface: teacherBrandPalette.neutral[0],
  surfaceSoft: teacherBrandPalette.neutral[50],
  surfaceMuted: teacherBrandPalette.neutral[100],
  pageGlass: 'rgba(255, 249, 246, 0.92)',
  surfaceGlass: 'rgba(255, 255, 255, 0.88)',
  textPrimary: teacherBrandPalette.neutral[900],
  textSecondary: teacherBrandPalette.neutral[500],
  textTertiary: teacherBrandPalette.neutral[550],
  textDisabled: teacherBrandPalette.neutral[400],
  border: teacherBrandPalette.neutral[200],
  borderControl: teacherBrandPalette.neutral[450],
  gridLine: teacherBrandPalette.neutral[100],
  mask: 'rgba(23, 21, 19, 0.42)',
  chartTooltip: 'rgba(23, 21, 19, 0.92)',
  chartHover: 'rgba(224, 39, 39, 0.06)',
} as const;

// 五育是固定分类（德智体美劳），可以固定配色；全部取自品牌色板，与学校自定义指标区分。
// 分类色必须满足白底 3:1 图形对比度：美育使用深薄荷，劳育使用深金。
// 体育与覆盖率同属绿色系是有意设计：分类场景（五育图表）与比例场景（覆盖进度）不共存于同一图表。
export const teacherFiveEducationSemantic = {
  virtue: teacherBrandPalette.red[500],
  wisdom: teacherBrandPalette.orange[500],
  fitness: teacherBrandPalette.green[500],
  aesthetic: teacherBrandPalette.mint[500],
  labor: teacherBrandPalette.gold[600],
} as const;

// 花名册头像、分组标签等不承载业务语义的低饱和点缀色，全部派生自品牌色板。
export const teacherTagTones = {
  jade: { soft: teacherBrandPalette.jade[50], strong: teacherBrandPalette.jade[700], border: teacherBrandPalette.jade[100] },
  orange: { soft: teacherBrandPalette.orange[50], strong: teacherBrandPalette.orange[700], border: teacherBrandPalette.orange[100] },
  red: { soft: teacherBrandPalette.red[50], strong: teacherBrandPalette.red[700], border: teacherBrandPalette.red[100] },
  gold: { soft: teacherBrandPalette.gold[50], strong: teacherBrandPalette.gold[700], border: teacherBrandPalette.gold[100] },
} as const;

export const teacherGenderSemantic = {
  male: teacherBrandPalette.jade[400],
  female: teacherBrandPalette.orange[500],
} as const;

export const teacherAssistantRoleSemantic = {
  headteacher: {
    primary: '#1F9E84',
    strong: '#126B5B',
    soft: '#EFFAF7',
    softStrong: '#D8F3EC',
    border: '#B7E7DB',
    highlight: '#86E0CC',
    glowPrimary: 'rgba(31, 158, 132, 0.14)',
    glowSecondary: 'rgba(134, 224, 204, 0.12)',
    shadow: 'rgba(18, 107, 91, 0.18)',
  },
  principal: {
    primary: teacherBrandPalette.red[500],
    strong: teacherBrandPalette.red[700],
    soft: teacherBrandPalette.red[50],
    softStrong: teacherBrandPalette.red[100],
    border: teacherBrandPalette.red[200],
    accent: teacherBrandPalette.gold[500],
    accentStrong: teacherBrandPalette.gold[700],
    highlight: teacherBrandPalette.gold[300],
    accentSoft: teacherBrandPalette.gold[50],
    accentBorder: teacherBrandPalette.gold[300],
    glowPrimary: 'rgba(224, 39, 39, 0.13)',
    glowSecondary: 'rgba(250, 156, 0, 0.11)',
    shadow: 'rgba(146, 34, 31, 0.18)',
  },
} as const;

export const teacherAudienceSemantic = {
  guardian: {
    primary: teacherBrandPalette.red[500],
    strong: teacherBrandPalette.red[700],
    soft: teacherBrandPalette.red[50],
    border: teacherBrandPalette.red[200],
  },
  student: {
    primary: teacherBrandPalette.jade[500],
    strong: teacherBrandPalette.jade[700],
    soft: teacherBrandPalette.jade[50],
    border: teacherBrandPalette.jade[200],
  },
  teacher: {
    primary: teacherBrandPalette.gold[500],
    strong: teacherBrandPalette.gold[700],
    soft: teacherBrandPalette.gold[50],
    border: teacherBrandPalette.gold[300],
  },
} as const;

export const teacherBrandCssVariables = {
  '--tm-brand-primary': teacherBrandSemantic.primary,
  '--tm-brand-primary-strong': teacherBrandSemantic.primaryStrong,
  '--tm-brand-primary-hover': teacherBrandSemantic.primaryHover,
  '--tm-brand-primary-pressed': teacherBrandSemantic.primaryPressed,
  '--tm-brand-primary-soft': teacherBrandSemantic.primarySoft,
  '--tm-brand-primary-soft-strong': teacherBrandSemantic.primarySoftStrong,
  '--tm-brand-secondary': teacherBrandSemantic.secondary,
  '--tm-brand-secondary-strong': teacherBrandSemantic.secondaryStrong,
  '--tm-brand-secondary-soft': teacherBrandSemantic.secondarySoft,
  '--tm-brand-reward': teacherBrandSemantic.reward,
  '--tm-brand-reward-strong': teacherBrandSemantic.rewardStrong,
  '--tm-brand-reward-soft': teacherBrandSemantic.rewardSoft,
  '--tm-status-positive': teacherBrandSemantic.positive,
  '--tm-status-positive-strong': teacherBrandSemantic.positiveStrong,
  '--tm-status-positive-soft': teacherBrandSemantic.positiveSoft,
  '--tm-status-negative': teacherBrandSemantic.negative,
  '--tm-status-negative-strong': teacherBrandSemantic.negativeStrong,
  '--tm-status-negative-soft': teacherBrandSemantic.negativeSoft,
  '--tm-record-student-primary': teacherBrandSemantic.primary,
  '--tm-record-student-text': teacherBrandSemantic.primaryStrong,
  '--tm-record-student-soft': teacherBrandSemantic.primarySoft,
  '--tm-record-student-soft-strong': teacherBrandSemantic.primarySoftStrong,
  '--tm-record-class-primary': teacherBrandSemantic.secondary,
  '--tm-record-class-text': teacherBrandSemantic.secondaryStrong,
  '--tm-record-class-soft': teacherBrandSemantic.secondarySoft,
  '--tm-record-positive-bg': teacherBrandSemantic.positiveSoft,
  '--tm-record-positive-border': teacherBrandPalette.green[100],
  '--tm-record-positive-text': teacherBrandSemantic.positiveStrong,
  '--tm-record-negative-bg': teacherBrandSemantic.negativeSoft,
  '--tm-record-negative-border': teacherBrandPalette.rose[100],
  '--tm-record-negative-text': teacherBrandSemantic.negativeStrong,
  '--tm-edu-virtue': teacherFiveEducationSemantic.virtue,
  '--tm-edu-wisdom': teacherFiveEducationSemantic.wisdom,
  '--tm-edu-fitness': teacherFiveEducationSemantic.fitness,
  '--tm-edu-aesthetic': teacherFiveEducationSemantic.aesthetic,
  '--tm-edu-labor': teacherFiveEducationSemantic.labor,
  '--tm-tag-jade-soft': teacherTagTones.jade.soft,
  '--tm-tag-jade-strong': teacherTagTones.jade.strong,
  '--tm-tag-jade-border': teacherTagTones.jade.border,
  '--tm-tag-orange-soft': teacherTagTones.orange.soft,
  '--tm-tag-orange-strong': teacherTagTones.orange.strong,
  '--tm-tag-orange-border': teacherTagTones.orange.border,
  '--tm-tag-red-soft': teacherTagTones.red.soft,
  '--tm-tag-red-strong': teacherTagTones.red.strong,
  '--tm-tag-red-border': teacherTagTones.red.border,
  '--tm-tag-gold-soft': teacherTagTones.gold.soft,
  '--tm-tag-gold-strong': teacherTagTones.gold.strong,
  '--tm-tag-gold-border': teacherTagTones.gold.border,
  '--tm-gender-male': teacherGenderSemantic.male,
  '--tm-gender-female': teacherGenderSemantic.female,
  '--tm-bg-page': teacherBrandSemantic.page,
  '--tm-bg-page-mid': teacherBrandSemantic.pageMid,
  '--tm-bg-page-low': teacherBrandSemantic.pageLow,
  '--tm-bg-surface': teacherBrandSemantic.surface,
  '--tm-bg-surface-soft': teacherBrandSemantic.surfaceSoft,
  '--tm-bg-surface-muted': teacherBrandSemantic.surfaceMuted,
  '--tm-bg-page-glass': teacherBrandSemantic.pageGlass,
  '--tm-bg-surface-glass': teacherBrandSemantic.surfaceGlass,
  '--tm-text-primary': teacherBrandSemantic.textPrimary,
  '--tm-text-secondary': teacherBrandSemantic.textSecondary,
  '--tm-text-tertiary': teacherBrandSemantic.textTertiary,
  '--tm-text-disabled': teacherBrandSemantic.textDisabled,
  '--tm-text-inverse': teacherBrandSemantic.surface,
  '--tm-nav-item-default': teacherBrandSemantic.textSecondary,
  '--tm-border-subtle': teacherBrandSemantic.border,
  '--tm-border-control': teacherBrandSemantic.borderControl,
  '--tm-chart-grid': teacherBrandSemantic.gridLine,
  '--tm-chart-tooltip': teacherBrandSemantic.chartTooltip,
  '--tm-chart-hover': teacherBrandSemantic.chartHover,
  // 对比系列：无正负含义的多系列对比。上周期为分类色 40% 透明度，外部参照统一中性浅灰，汇总/净得分使用深中性。
  '--tm-chart-series-muted-opacity': '0.4',
  '--tm-chart-series-peer': teacherBrandPalette.neutral[300],
  '--tm-chart-series-total': teacherBrandPalette.neutral[700],
  '--tm-focus-ring': teacherBrandSemantic.primary,
  '--tm-mask': teacherBrandSemantic.mask,
  '--tm-shadow-brand-color': 'rgba(224, 39, 39, 0.30)',
  '--tm-shadow-neutral-color': 'rgba(64, 60, 58, 0.18)',
  '--tm-shadow-card': '0 10px 28px -20px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-card-raised': '0 12px 32px -26px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-control': '0 6px 16px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-icon': '0 10px 22px -16px rgba(224, 39, 39, 0.24)',
  '--tm-shadow-avatar': '0 18px 28px -18px rgba(224, 39, 39, 0.24)',
  '--tm-shadow-floating': '0 -10px 24px -12px rgba(64, 60, 58, 0.18), 0 10px 28px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-navigation': '0 -10px 24px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-sheet': '0 -20px 52px -34px rgba(64, 60, 58, 0.18)',
  '--tm-glow-primary': 'rgba(224, 39, 39, 0.13)',
  '--tm-glow-secondary': 'rgba(247, 92, 3, 0.11)',
  '--tm-glow-primary-subtle': 'rgba(224, 39, 39, 0.055)',
  '--tm-glow-secondary-subtle': 'rgba(247, 92, 3, 0.05)',
  '--tm-role-headteacher-primary': teacherAssistantRoleSemantic.headteacher.primary,
  '--tm-role-headteacher-strong': teacherAssistantRoleSemantic.headteacher.strong,
  '--tm-role-headteacher-soft': teacherAssistantRoleSemantic.headteacher.soft,
  '--tm-role-headteacher-soft-strong': teacherAssistantRoleSemantic.headteacher.softStrong,
  '--tm-role-headteacher-border': teacherAssistantRoleSemantic.headteacher.border,
  '--tm-role-headteacher-highlight': teacherAssistantRoleSemantic.headteacher.highlight,
  '--tm-role-headteacher-glow-primary': teacherAssistantRoleSemantic.headteacher.glowPrimary,
  '--tm-role-headteacher-glow-secondary': teacherAssistantRoleSemantic.headteacher.glowSecondary,
  '--tm-role-headteacher-shadow': teacherAssistantRoleSemantic.headteacher.shadow,
  '--tm-role-principal-primary': teacherAssistantRoleSemantic.principal.primary,
  '--tm-role-principal-strong': teacherAssistantRoleSemantic.principal.strong,
  '--tm-role-principal-soft': teacherAssistantRoleSemantic.principal.soft,
  '--tm-role-principal-soft-strong': teacherAssistantRoleSemantic.principal.softStrong,
  '--tm-role-principal-border': teacherAssistantRoleSemantic.principal.border,
  '--tm-role-principal-accent': teacherAssistantRoleSemantic.principal.accent,
  '--tm-role-principal-accent-strong': teacherAssistantRoleSemantic.principal.accentStrong,
  '--tm-role-principal-highlight': teacherAssistantRoleSemantic.principal.highlight,
  '--tm-role-principal-accent-soft': teacherAssistantRoleSemantic.principal.accentSoft,
  '--tm-role-principal-accent-border': teacherAssistantRoleSemantic.principal.accentBorder,
  '--tm-role-principal-glow-primary': teacherAssistantRoleSemantic.principal.glowPrimary,
  '--tm-role-principal-glow-secondary': teacherAssistantRoleSemantic.principal.glowSecondary,
  '--tm-role-principal-shadow': teacherAssistantRoleSemantic.principal.shadow,
  '--tm-audience-guardian-primary': teacherAudienceSemantic.guardian.primary,
  '--tm-audience-guardian-strong': teacherAudienceSemantic.guardian.strong,
  '--tm-audience-guardian-soft': teacherAudienceSemantic.guardian.soft,
  '--tm-audience-guardian-border': teacherAudienceSemantic.guardian.border,
  '--tm-audience-student-primary': teacherAudienceSemantic.student.primary,
  '--tm-audience-student-strong': teacherAudienceSemantic.student.strong,
  '--tm-audience-student-soft': teacherAudienceSemantic.student.soft,
  '--tm-audience-student-border': teacherAudienceSemantic.student.border,
  '--tm-audience-teacher-primary': teacherAudienceSemantic.teacher.primary,
  '--tm-audience-teacher-strong': teacherAudienceSemantic.teacher.strong,
  '--tm-audience-teacher-soft': teacherAudienceSemantic.teacher.soft,
  '--tm-audience-teacher-border': teacherAudienceSemantic.teacher.border,
  '--tm-radius-control': '12px',
  '--tm-radius-inner': '16px',
  '--tm-radius-card': '20px',
  '--tm-radius-sheet': '28px',
  '--tm-size-touch': '44px',
  '--tm-font-size-page-title': '22px',
  '--tm-font-size-section-title': '17px',
  '--tm-font-size-card-title': '15px',
  '--tm-font-size-body': '14px',
  '--tm-font-size-compact': '13px',
  '--tm-font-size-meta': '12px',
  '--tm-font-size-badge': '11px',
  '--tm-font-size-metric': '24px',
  '--tm-space-1': '4px',
  '--tm-space-2': '8px',
  '--tm-space-3': '12px',
  '--tm-space-4': '16px',
  '--tm-space-5': '20px',
  '--tm-space-6': '24px',
  '--tm-space-8': '32px',
  '--tm-duration-fast': '150ms',
  '--tm-duration-standard': '200ms',
  '--tm-duration-panel': '300ms',
} satisfies Record<`--${string}`, string>;

export const phoneText = {
  navTitle: 'text-[17px] font-bold leading-tight',
  pageTitle: 'text-[22px] font-bold leading-tight',
  sectionTitle: 'text-[17px] font-semibold leading-snug',
  itemTitle: 'text-[15px] font-normal leading-snug',
  body: 'text-[14px] font-medium leading-relaxed',
  helper: 'text-[12px] font-normal leading-snug',
  label: 'text-[11px] font-bold leading-none',
  metric: 'text-[24px] font-bold leading-none',
} as const;

export const phoneRadius = {
  sm: 'rounded-[8px]',
  md: 'rounded-[12px]',
  lg: 'rounded-[16px]',
  xl: 'rounded-[20px]',
  sheet: 'rounded-[28px]',
  full: 'rounded-full',
} as const;

export const phoneShadow = {
  none: 'shadow-none',
  card: 'shadow-[var(--tm-shadow-card)]',
  raised: 'shadow-[var(--tm-shadow-card-raised)]',
  floating: 'shadow-[var(--tm-shadow-floating)]',
  modal: 'shadow-[var(--tm-shadow-sheet)]',
} as const;

export const phoneSpace = {
  pageX: 'px-5',
  sectionGap: 'space-y-5',
  cardMd: 'p-4',
  cardLg: 'p-6',
} as const;

export const phoneTone = {
  brand: {
    box: 'border-[var(--tm-brand-primary-soft-strong)] bg-[var(--tm-brand-primary-soft)] text-[var(--tm-brand-primary)]',
    soft: 'border-[var(--tm-brand-primary-soft-strong)] bg-[var(--tm-brand-primary-soft)] text-[var(--tm-brand-primary-pressed)]',
  },
  secondary: {
    box: 'border-[var(--tm-brand-secondary)]/20 bg-[var(--tm-brand-secondary-soft)] text-[var(--tm-brand-secondary-strong)]',
    soft: 'border-[var(--tm-brand-secondary)]/20 bg-[var(--tm-brand-secondary-soft)] text-[var(--tm-brand-secondary-strong)]',
  },
  reward: {
    box: 'border-[var(--tm-brand-reward)]/20 bg-[var(--tm-brand-reward-soft)] text-[var(--tm-brand-reward-strong)]',
    soft: 'border-[var(--tm-brand-reward)]/20 bg-[var(--tm-brand-reward-soft)] text-[var(--tm-brand-reward-strong)]',
  },
  positive: {
    box: 'border-[var(--tm-status-positive)]/20 bg-[var(--tm-status-positive-soft)] text-[var(--tm-status-positive-strong)]',
    soft: 'border-[var(--tm-status-positive)]/20 bg-[var(--tm-status-positive-soft)] text-[var(--tm-status-positive-strong)]',
  },
  negative: {
    box: 'border-[var(--tm-status-negative)]/20 bg-[var(--tm-status-negative-soft)] text-[var(--tm-status-negative-strong)]',
    soft: 'border-[var(--tm-status-negative)]/20 bg-[var(--tm-status-negative-soft)] text-[var(--tm-status-negative-strong)]',
  },
  neutral: {
    box: 'border-[var(--tm-border-subtle)] bg-[var(--tm-bg-surface-soft)] text-[var(--tm-text-secondary)]',
    soft: 'border-[var(--tm-border-subtle)] bg-[var(--tm-bg-surface-soft)] text-[var(--tm-text-secondary)]',
  },
} as const;

export type PhoneTone = keyof typeof phoneTone;
