import { questionnaireThemePalette } from '../../shared/questionnaireThemeTokens';

export const teacherBrandPalette = {
  red: {
    ...questionnaireThemePalette.red,
    300: '#F99A98',
    400: '#EE615F',
    800: '#92221F',
    900: '#731B1A',
  },
  orange: {
    50: '#FFF5EC',
    100: '#FFE8D4',
    200: '#FFD0A5',
    300: '#FFB56F',
    400: '#FF8B33',
    500: '#F75C03',
    600: '#D94E00',
    700: '#B83F00',
    800: '#913406',
    900: '#762D0B',
  },
  gold: {
    50: '#FFF8E5',
    100: '#FFEFC2',
    200: '#FFE294',
    300: '#FFD56A',
    400: '#FDB63A',
    500: '#FA9C00',
    600: '#C88100',
    700: '#9A5B00',
    800: '#7A4900',
    900: '#5C3800',
  },
  jade: {
    50: '#ECF8F6',
    100: '#D4EEE9',
    200: '#ADDCD4',
    300: '#79C3B7',
    400: '#2CCBA3',
    500: '#278779',
    600: '#1C7167',
    700: '#155B54',
    800: '#124943',
    900: '#103D38',
  },
  neutral: {
    ...questionnaireThemePalette.neutral,
    25: '#FFFCFA',
    300: '#D2CBC7',
    700: '#403C3A',
  },
  // 深薄荷：仅用于五育-美育分类，与玉石青受众色、体育绿区分。
  mint: {
    500: '#14A085',
  },
  green: {
    ...questionnaireThemePalette.green,
    100: '#D4EAD5',
  },
} as const;

export const teacherPlatformPalette = {
  wechat: {
    500: '#07C160',
    600: '#06AD56',
  },
} as const;

export const teacherPlatformSemantic = {
  wechat: teacherPlatformPalette.wechat[500],
  wechatPressed: teacherPlatformPalette.wechat[600],
} as const;

export const teacherBrandSemantic = {
  primary: teacherBrandPalette.red[500],
  primaryStrong: teacherBrandPalette.red[700],
  primaryHover: teacherBrandPalette.red[600],
  primaryPressed: teacherBrandPalette.red[700],
  primarySoft: teacherBrandPalette.red[50],
  primarySoftStrong: teacherBrandPalette.red[100],
  secondary: teacherBrandPalette.orange[500],
  secondaryStrong: teacherBrandPalette.orange[700],
  secondarySoft: teacherBrandPalette.orange[50],
  reward: teacherBrandPalette.gold[500],
  rewardStrong: teacherBrandPalette.gold[700],
  rewardSoft: teacherBrandPalette.gold[50],
  positive: teacherBrandPalette.green[500],
  positiveStrong: teacherBrandPalette.green[700],
  positiveSoft: teacherBrandPalette.green[50],
  negative: teacherBrandPalette.red[500],
  negativeStrong: teacherBrandPalette.red[700],
  negativeSoft: teacherBrandPalette.red[50],
  page: '#F8F6F5',
  pageMid: '#FBFAF9',
  pageLow: '#F6F4F3',
  surface: teacherBrandPalette.neutral[0],
  surfaceSoft: teacherBrandPalette.neutral[50],
  surfaceMuted: teacherBrandPalette.neutral[100],
  pageGlass: 'rgba(255, 249, 246, 0.92)',
  surfaceGlass: 'rgba(255, 255, 255, 0.96)',
  textPrimary: teacherBrandPalette.neutral[900],
  textSecondary: teacherBrandPalette.neutral[500],
  textTertiary: teacherBrandPalette.neutral[550],
  textDisabled: teacherBrandPalette.neutral[400],
  border: teacherBrandPalette.neutral[200],
  borderControl: teacherBrandPalette.neutral[450],
  gridLine: teacherBrandPalette.neutral[100],
  mask: 'rgba(23, 21, 19, 0.42)',
  chartTooltip: 'rgba(23, 21, 19, 0.92)',
  chartHover: 'rgba(224, 39, 39, 0.06)',
} as const;

export const teacherActionSemantic = {
  iconNeutral: teacherBrandSemantic.textSecondary,
  iconBrand: teacherBrandSemantic.primary,
  iconDanger: teacherBrandSemantic.negative,
} as const;

// “我的”页方案八：品牌红与清亮蓝从两侧低饱和扩散，玉石青只保留为顶部轻提示。
export const teacherMePageGradientSemantic = {
  base: teacherBrandPalette.red[50],
  primaryField: 'rgba(224, 39, 39, 0.16)',
  skyField: 'rgba(67, 176, 246, 0.14)',
  jadeHint: 'rgba(39, 135, 121, 0.04)',
  tailField: 'rgba(67, 176, 246, 0.05)',
} as const;

// 报表图形使用清亮填充色；深色只服务于数值、标签与必要边界。
export const teacherReportChartPalette = {
  sky: { soft: '#F4FAFF', fill: '#43B0F6', text: '#176B9B' },
  spring: { soft: '#F3FFF6', fill: '#5BD65D', text: '#23733A' },
  orange: { soft: '#FFFAEE', fill: '#FF9B3D', text: '#9C5118' },
  coral: { soft: '#FFF7F4', fill: '#FF8176', text: '#A8433D' },
  cyan: { fill: '#45CED1' },
  amber: { fill: '#FFB84D' },
  blueGray: {
    soft: '#F3F6F8',
    peer: '#AFBDCB',
    total: '#40566D',
    grid: '#E8F0F5',
    tooltip: '#17213A',
  },
} as const;

export const teacherReportChartSemantic = {
  dataDefault: teacherReportChartPalette.sky.fill,
  dataDefaultText: teacherReportChartPalette.sky.text,
  dataDefaultSoft: teacherReportChartPalette.sky.soft,
  percentage: {
    low: teacherReportChartPalette.coral,
    medium: teacherReportChartPalette.orange,
    high: teacherReportChartPalette.spring,
  },
  positive: teacherReportChartPalette.spring.fill,
  positiveText: teacherReportChartPalette.spring.text,
  positiveSoft: teacherReportChartPalette.spring.soft,
  warning: teacherReportChartPalette.orange.fill,
  warningText: teacherReportChartPalette.orange.text,
  warningSoft: teacherReportChartPalette.orange.soft,
  negative: teacherReportChartPalette.coral.fill,
  negativeText: teacherReportChartPalette.coral.text,
  negativeSoft: teacherReportChartPalette.coral.soft,
  peer: teacherReportChartPalette.blueGray.peer,
  total: teacherReportChartPalette.blueGray.total,
  grid: teacherReportChartPalette.blueGray.grid,
  tooltip: teacherReportChartPalette.blueGray.tooltip,
  education: {
    virtue: teacherReportChartPalette.coral.fill,
    wisdom: teacherReportChartPalette.sky.fill,
    fitness: teacherReportChartPalette.spring.fill,
    aesthetic: teacherReportChartPalette.cyan.fill,
    labor: teacherReportChartPalette.amber.fill,
  },
  indicators: [
    teacherReportChartPalette.coral.fill,
    teacherReportChartPalette.sky.fill,
    teacherReportChartPalette.spring.fill,
    teacherReportChartPalette.cyan.fill,
    teacherReportChartPalette.amber.fill,
    teacherBrandPalette.red[700],
  ],
} as const;

// 评价指标标签只表达同一条指标路径，不用色阶暗示额外层级含义。
export const teacherEvaluationIndicatorSemantic = {
  text: '#35566E',
  separator: '#85A0B3',
  background: '#F3F8FC',
  border: '#DFEBF4',
} as const;

// 评价原始记录使用独立的浅雾蓝内容面板，和指标标签保持协调但不共享组件语义。
export const teacherEvaluationSourceSemantic = {
  background: '#F3F8FC',
  border: '#D5E5F0',
  controlText: teacherReportChartSemantic.dataDefaultText,
} as const;

// AI识别结果中的可编辑值沿用已有数据蓝，通过独立语义避免业务组件直接引用图表变量。
export const teacherEvaluationAiSemantic = {
  editableText: teacherReportChartSemantic.dataDefaultText,
} as const;

// 指标编辑使用数据蓝的浅色状态，表达可选中而不引入品牌红的大面积填充。
export const teacherEvaluationIndicatorEditorSemantic = {
  border: teacherEvaluationSourceSemantic.border,
  headerBackground: teacherReportChartSemantic.dataDefaultSoft,
  selectedBackground: teacherReportChartSemantic.dataDefaultSoft,
  selectedText: teacherReportChartSemantic.dataDefaultText,
  focusRing: teacherReportChartSemantic.dataDefault,
  activeBackground: teacherEvaluationIndicatorSemantic.background,
} as const;

// 标准德智体美劳图表仍可使用固定配色；班级报告的学校自定义一级指标使用 indicators 循环色板。
// 分类色必须满足白底 3:1 图形对比度：美育使用深薄荷，劳育使用深金。
// 体育与覆盖率同属绿色系是有意设计：分类场景（五育图表）与比例场景（覆盖进度）不共存于同一图表。
export const teacherFiveEducationSemantic = {
  virtue: teacherBrandPalette.red[500],
  wisdom: teacherBrandPalette.orange[500],
  fitness: teacherBrandPalette.green[500],
  aesthetic: teacherBrandPalette.mint[500],
  labor: teacherBrandPalette.gold[600],
} as const;

// 花名册头像、分组标签等不承载业务语义的低饱和点缀色，全部派生自品牌色板。
export const teacherTagTones = {
  jade: { soft: teacherBrandPalette.jade[50], strong: teacherBrandPalette.jade[700], border: teacherBrandPalette.jade[100] },
  orange: { soft: teacherBrandPalette.orange[50], strong: teacherBrandPalette.orange[700], border: teacherBrandPalette.orange[100] },
  red: { soft: teacherBrandPalette.red[50], strong: teacherBrandPalette.red[700], border: teacherBrandPalette.red[100] },
  gold: { soft: teacherBrandPalette.gold[50], strong: teacherBrandPalette.gold[700], border: teacherBrandPalette.gold[100] },
} as const;

export const teacherGenderSemantic = {
  male: {
    soft: teacherReportChartPalette.spring.soft,
    base: teacherReportChartPalette.spring.fill,
    strong: teacherReportChartPalette.spring.text,
    selectionBackground: teacherReportChartPalette.spring.fill,
  },
  female: {
    soft: teacherReportChartPalette.coral.soft,
    base: teacherReportChartPalette.coral.fill,
    strong: teacherReportChartPalette.coral.text,
    selectionBackground: teacherReportChartPalette.coral.fill,
  },
} as const;

export const teacherStudentLevelSemantic = {
  reward: teacherBrandPalette.gold[600],
  progress: teacherBrandPalette.gold[500],
  track: teacherBrandPalette.neutral[100],
  praise: teacherBrandPalette.green[700],
  praiseSoft: teacherBrandPalette.green[50],
  criticism: teacherBrandPalette.red[700],
  criticismSoft: teacherBrandPalette.red[50],
} as const;

// 档案外观主题在档案容器内覆盖主操作色；错误、删除等状态色仍使用全局语义。
export const teacherArchiveAppearanceSemantic = {
  clean: {
    background: '#F7F7F8',
    swatch: teacherBrandPalette.neutral[0],
    accent: teacherBrandSemantic.primary,
    accentStrong: teacherBrandSemantic.primaryStrong,
    accentPressed: teacherBrandSemantic.primaryPressed,
    accentSoft: teacherBrandSemantic.primarySoft,
    accentSoftStrong: teacherBrandSemantic.primarySoftStrong,
  },
  sky: {
    background: '#F2F7FA',
    swatch: '#DDECF5',
    accent: '#2F789C',
    accentStrong: '#205B78',
    accentPressed: '#194A62',
    accentSoft: '#E3F0F6',
    accentSoftStrong: '#D3E6EF',
  },
  leaf: {
    background: '#F3F7F1',
    swatch: '#E1ECD9',
    accent: '#4F7A43',
    accentStrong: '#375C2F',
    accentPressed: '#2B4925',
    accentSoft: '#E8F1E4',
    accentSoftStrong: '#D8E8D1',
  },
  sunny: {
    background: '#FAF7EF',
    swatch: '#F4E8C6',
    accent: '#A86716',
    accentStrong: '#7D4B0B',
    accentPressed: '#663C08',
    accentSoft: '#F8EBCF',
    accentSoftStrong: '#F0D9AA',
  },
} as const;

export const teacherAssistantRoleSemantic = {
  headteacher: {
    primary: '#1F9E84',
    strong: '#126B5B',
    soft: '#EFFAF7',
    softStrong: '#D8F3EC',
    border: '#B7E7DB',
    highlight: '#86E0CC',
    glowPrimary: 'rgba(31, 158, 132, 0.14)',
    glowSecondary: 'rgba(134, 224, 204, 0.12)',
    shadow: 'rgba(18, 107, 91, 0.18)',
    pageGradientStart: '#E8F8F3',
    pageGradientMiddle: '#F0F4FF',
    pageGradientEnd: '#F8F4F8',
    glassSurface: 'rgba(255, 255, 255, 0.58)',
    glassSurfaceStrong: 'rgba(255, 255, 255, 0.76)',
    glassBorder: 'rgba(255, 255, 255, 0.88)',
    glassShadow: 'rgba(54, 82, 78, 0.24)',
    contextSurface: 'rgba(255, 255, 255, 0.72)',
    dataSurface: 'rgba(239, 250, 247, 0.90)',
    contextShadow: '0 2px 4px -2px rgba(54, 82, 78, 0.16), 0 20px 46px -28px rgba(54, 82, 78, 0.28), inset 0 1px 0 rgba(255, 255, 255, 0.82)',
    dataShadow: '0 1px 3px rgba(18, 107, 91, 0.08), 0 12px 26px -18px rgba(18, 107, 91, 0.16)',
  },
  principal: {
    primary: teacherBrandPalette.red[500],
    strong: teacherBrandPalette.red[700],
    soft: teacherBrandPalette.red[50],
    softStrong: teacherBrandPalette.red[100],
    border: teacherBrandPalette.red[200],
    accent: teacherBrandPalette.gold[500],
    accentStrong: teacherBrandPalette.gold[700],
    highlight: teacherBrandPalette.gold[300],
    accentSoft: teacherBrandPalette.gold[50],
    accentBorder: teacherBrandPalette.gold[300],
    glowPrimary: 'rgba(224, 39, 39, 0.13)',
    glowSecondary: 'rgba(250, 156, 0, 0.11)',
    shadow: 'rgba(146, 34, 31, 0.18)',
  },
} as const;

export const teacherAudienceSemantic = {
  guardian: {
    primary: teacherBrandPalette.red[500],
    strong: teacherBrandPalette.red[700],
    soft: teacherBrandPalette.red[50],
    border: teacherBrandPalette.red[200],
  },
  student: {
    primary: teacherBrandPalette.jade[500],
    strong: teacherBrandPalette.jade[700],
    soft: teacherBrandPalette.jade[50],
    border: teacherBrandPalette.jade[200],
  },
  teacher: {
    primary: teacherBrandPalette.gold[500],
    strong: teacherBrandPalette.gold[700],
    soft: teacherBrandPalette.gold[50],
    border: teacherBrandPalette.gold[300],
  },
} as const;

export const teacherBrandCssVariables = {
  '--tm-brand-primary': teacherBrandSemantic.primary,
  '--tm-brand-primary-strong': teacherBrandSemantic.primaryStrong,
  '--tm-brand-primary-hover': teacherBrandSemantic.primaryHover,
  '--tm-brand-primary-pressed': teacherBrandSemantic.primaryPressed,
  '--tm-brand-primary-soft': teacherBrandSemantic.primarySoft,
  '--tm-brand-primary-soft-strong': teacherBrandSemantic.primarySoftStrong,
  '--tm-brand-secondary': teacherBrandSemantic.secondary,
  '--tm-brand-secondary-strong': teacherBrandSemantic.secondaryStrong,
  '--tm-brand-secondary-soft': teacherBrandSemantic.secondarySoft,
  '--tm-brand-reward': teacherBrandSemantic.reward,
  '--tm-brand-reward-strong': teacherBrandSemantic.rewardStrong,
  '--tm-brand-reward-soft': teacherBrandSemantic.rewardSoft,
  '--tm-platform-wechat': teacherPlatformSemantic.wechat,
  '--tm-platform-wechat-pressed': teacherPlatformSemantic.wechatPressed,
  '--tm-status-positive': teacherBrandSemantic.positive,
  '--tm-status-positive-strong': teacherBrandSemantic.positiveStrong,
  '--tm-status-positive-soft': teacherBrandSemantic.positiveSoft,
  '--tm-status-negative': teacherBrandSemantic.negative,
  '--tm-status-negative-strong': teacherBrandSemantic.negativeStrong,
  '--tm-status-negative-soft': teacherBrandSemantic.negativeSoft,
  '--tm-record-student-primary': teacherBrandSemantic.primary,
  '--tm-record-student-text': teacherBrandSemantic.primaryStrong,
  '--tm-record-student-soft': teacherBrandSemantic.primarySoft,
  '--tm-record-student-soft-strong': teacherBrandSemantic.primarySoftStrong,
  '--tm-record-class-primary': teacherBrandSemantic.secondary,
  '--tm-record-class-text': teacherBrandSemantic.secondaryStrong,
  '--tm-record-class-soft': teacherBrandSemantic.secondarySoft,
  '--tm-record-scope-visual-height': '36px',
  '--tm-record-positive-bg': teacherBrandSemantic.positiveSoft,
  '--tm-record-positive-border': teacherBrandPalette.green[100],
  '--tm-record-positive-text': teacherBrandSemantic.positiveStrong,
  '--tm-record-negative-bg': teacherBrandSemantic.negativeSoft,
  '--tm-record-negative-border': teacherBrandPalette.red[100],
  '--tm-record-negative-text': teacherBrandSemantic.negativeStrong,
  '--tm-edu-virtue': teacherFiveEducationSemantic.virtue,
  '--tm-edu-wisdom': teacherFiveEducationSemantic.wisdom,
  '--tm-edu-fitness': teacherFiveEducationSemantic.fitness,
  '--tm-edu-aesthetic': teacherFiveEducationSemantic.aesthetic,
  '--tm-edu-labor': teacherFiveEducationSemantic.labor,
  '--tm-tag-jade-soft': teacherTagTones.jade.soft,
  '--tm-tag-jade-strong': teacherTagTones.jade.strong,
  '--tm-tag-jade-border': teacherTagTones.jade.border,
  '--tm-tag-orange-soft': teacherTagTones.orange.soft,
  '--tm-tag-orange-strong': teacherTagTones.orange.strong,
  '--tm-tag-orange-border': teacherTagTones.orange.border,
  '--tm-tag-red-soft': teacherTagTones.red.soft,
  '--tm-tag-red-strong': teacherTagTones.red.strong,
  '--tm-tag-red-border': teacherTagTones.red.border,
  '--tm-tag-gold-soft': teacherTagTones.gold.soft,
  '--tm-tag-gold-strong': teacherTagTones.gold.strong,
  '--tm-tag-gold-border': teacherTagTones.gold.border,
  '--tm-gender-male': teacherGenderSemantic.male.base,
  '--tm-gender-male-soft': teacherGenderSemantic.male.soft,
  '--tm-gender-male-strong': teacherGenderSemantic.male.strong,
  '--tm-gender-male-selection-bg': teacherGenderSemantic.male.selectionBackground,
  '--tm-gender-female': teacherGenderSemantic.female.base,
  '--tm-gender-female-soft': teacherGenderSemantic.female.soft,
  '--tm-gender-female-strong': teacherGenderSemantic.female.strong,
  '--tm-gender-female-selection-bg': teacherGenderSemantic.female.selectionBackground,
  '--tm-student-level-reward': teacherStudentLevelSemantic.reward,
  '--tm-student-level-progress': teacherStudentLevelSemantic.progress,
  '--tm-student-level-track': teacherStudentLevelSemantic.track,
  '--tm-student-praise': teacherStudentLevelSemantic.praise,
  '--tm-student-praise-soft': teacherStudentLevelSemantic.praiseSoft,
  '--tm-student-criticism': teacherStudentLevelSemantic.criticism,
  '--tm-student-criticism-soft': teacherStudentLevelSemantic.criticismSoft,
  '--tm-student-card-height-full': '120px',
  '--tm-student-card-height-compact': '104px',
  '--tm-student-card-height-minimal': '88px',
  '--tm-archive-theme-clean-bg': teacherArchiveAppearanceSemantic.clean.background,
  '--tm-archive-theme-clean-swatch': teacherArchiveAppearanceSemantic.clean.swatch,
  '--tm-archive-theme-clean-accent': teacherArchiveAppearanceSemantic.clean.accent,
  '--tm-archive-theme-clean-accent-strong': teacherArchiveAppearanceSemantic.clean.accentStrong,
  '--tm-archive-theme-clean-accent-pressed': teacherArchiveAppearanceSemantic.clean.accentPressed,
  '--tm-archive-theme-clean-accent-soft': teacherArchiveAppearanceSemantic.clean.accentSoft,
  '--tm-archive-theme-clean-accent-soft-strong': teacherArchiveAppearanceSemantic.clean.accentSoftStrong,
  '--tm-archive-theme-sky-bg': teacherArchiveAppearanceSemantic.sky.background,
  '--tm-archive-theme-sky-swatch': teacherArchiveAppearanceSemantic.sky.swatch,
  '--tm-archive-theme-sky-accent': teacherArchiveAppearanceSemantic.sky.accent,
  '--tm-archive-theme-sky-accent-strong': teacherArchiveAppearanceSemantic.sky.accentStrong,
  '--tm-archive-theme-sky-accent-pressed': teacherArchiveAppearanceSemantic.sky.accentPressed,
  '--tm-archive-theme-sky-accent-soft': teacherArchiveAppearanceSemantic.sky.accentSoft,
  '--tm-archive-theme-sky-accent-soft-strong': teacherArchiveAppearanceSemantic.sky.accentSoftStrong,
  '--tm-archive-theme-leaf-bg': teacherArchiveAppearanceSemantic.leaf.background,
  '--tm-archive-theme-leaf-swatch': teacherArchiveAppearanceSemantic.leaf.swatch,
  '--tm-archive-theme-leaf-accent': teacherArchiveAppearanceSemantic.leaf.accent,
  '--tm-archive-theme-leaf-accent-strong': teacherArchiveAppearanceSemantic.leaf.accentStrong,
  '--tm-archive-theme-leaf-accent-pressed': teacherArchiveAppearanceSemantic.leaf.accentPressed,
  '--tm-archive-theme-leaf-accent-soft': teacherArchiveAppearanceSemantic.leaf.accentSoft,
  '--tm-archive-theme-leaf-accent-soft-strong': teacherArchiveAppearanceSemantic.leaf.accentSoftStrong,
  '--tm-archive-theme-sunny-bg': teacherArchiveAppearanceSemantic.sunny.background,
  '--tm-archive-theme-sunny-swatch': teacherArchiveAppearanceSemantic.sunny.swatch,
  '--tm-archive-theme-sunny-accent': teacherArchiveAppearanceSemantic.sunny.accent,
  '--tm-archive-theme-sunny-accent-strong': teacherArchiveAppearanceSemantic.sunny.accentStrong,
  '--tm-archive-theme-sunny-accent-pressed': teacherArchiveAppearanceSemantic.sunny.accentPressed,
  '--tm-archive-theme-sunny-accent-soft': teacherArchiveAppearanceSemantic.sunny.accentSoft,
  '--tm-archive-theme-sunny-accent-soft-strong': teacherArchiveAppearanceSemantic.sunny.accentSoftStrong,
  '--tm-bg-page': teacherBrandSemantic.page,
  '--tm-bg-page-mid': teacherBrandSemantic.pageMid,
  '--tm-bg-page-low': teacherBrandSemantic.pageLow,
  '--tm-bg-surface': teacherBrandSemantic.surface,
  '--tm-bg-surface-soft': teacherBrandSemantic.surfaceSoft,
  '--tm-bg-surface-muted': teacherBrandSemantic.surfaceMuted,
  '--tm-bg-page-glass': teacherBrandSemantic.pageGlass,
  '--tm-bg-surface-glass': teacherBrandSemantic.surfaceGlass,
  '--tm-me-gradient-base': teacherMePageGradientSemantic.base,
  '--tm-me-gradient-primary-field': teacherMePageGradientSemantic.primaryField,
  '--tm-me-gradient-sky-field': teacherMePageGradientSemantic.skyField,
  '--tm-me-gradient-jade-hint': teacherMePageGradientSemantic.jadeHint,
  '--tm-me-gradient-tail-field': teacherMePageGradientSemantic.tailField,
  // 无渐变分层页面：状态栏与标题栏纯白，内容区浅灰，用于承托白色卡片。
  '--tm-page-plain-header-bg': teacherBrandSemantic.surface,
  '--tm-page-plain-content-bg': teacherBrandSemantic.surfaceSoft,
  '--tm-text-primary': teacherBrandSemantic.textPrimary,
  '--tm-text-secondary': teacherBrandSemantic.textSecondary,
  '--tm-text-tertiary': teacherBrandSemantic.textTertiary,
  '--tm-text-disabled': teacherBrandSemantic.textDisabled,
  '--tm-text-inverse': teacherBrandSemantic.surface,
  '--tm-action-icon-neutral': teacherActionSemantic.iconNeutral,
  '--tm-action-icon-brand': teacherActionSemantic.iconBrand,
  '--tm-action-icon-danger': teacherActionSemantic.iconDanger,
  '--tm-nav-item-default': teacherBrandSemantic.textSecondary,
  '--tm-border-subtle': teacherBrandSemantic.border,
  '--tm-border-control': teacherBrandSemantic.borderControl,
  '--tm-input-bg': teacherBrandSemantic.surface,
  '--tm-input-border': teacherBrandSemantic.border,
  '--tm-input-text': teacherBrandSemantic.textPrimary,
  '--tm-input-placeholder': teacherBrandSemantic.textTertiary,
  '--tm-input-disabled-bg': teacherBrandSemantic.surfaceMuted,
  '--tm-input-disabled-border': teacherBrandSemantic.border,
  '--tm-input-disabled-text': teacherBrandSemantic.textDisabled,
  '--tm-input-readonly-bg': teacherBrandSemantic.surfaceSoft,
  '--tm-input-readonly-border': teacherBrandSemantic.border,
  '--tm-input-readonly-text': teacherBrandSemantic.textSecondary,
  // 手机端输入聚焦保持默认中性边界；光标和软键盘已能反馈编辑状态，避免品牌红被误解为校验错误。
  '--tm-input-focus-border': teacherBrandSemantic.border,
  // 手机端筛选型下拉只保留文字、箭头和系统选择面板，不为默认、有值或激活状态增加容器视觉。
  '--tm-filter-bg': 'transparent',
  '--tm-filter-border': 'transparent',
  '--tm-filter-shadow': 'none',
  '--tm-filter-focus-bg': 'transparent',
  '--tm-filter-focus-outline': 'none',
  // 紧凑行编辑器：通过独立白色条目和浅边界承载高密度横向输入，避免形成深色表格网格。
  '--tm-compact-editor-row-bg': teacherBrandSemantic.surface,
  '--tm-compact-editor-control-bg': teacherBrandSemantic.surface,
  '--tm-compact-editor-control-border': teacherBrandSemantic.border,
  '--tm-compact-editor-selected-bg': teacherBrandSemantic.primary,
  '--tm-compact-editor-selected-text': teacherBrandSemantic.surface,
  '--tm-chart-data-default': teacherReportChartSemantic.dataDefault,
  '--tm-chart-data-default-text': teacherReportChartSemantic.dataDefaultText,
  '--tm-chart-data-default-soft': teacherReportChartSemantic.dataDefaultSoft,
  '--tm-evaluation-indicator-text': teacherEvaluationIndicatorSemantic.text,
  '--tm-evaluation-indicator-separator': teacherEvaluationIndicatorSemantic.separator,
  '--tm-evaluation-indicator-bg': teacherEvaluationIndicatorSemantic.background,
  '--tm-evaluation-indicator-border': teacherEvaluationIndicatorSemantic.border,
  '--tm-evaluation-source-bg': teacherEvaluationSourceSemantic.background,
  '--tm-evaluation-source-border': teacherEvaluationSourceSemantic.border,
  '--tm-evaluation-source-control-text': teacherEvaluationSourceSemantic.controlText,
  '--tm-evaluation-ai-editable-text': teacherEvaluationAiSemantic.editableText,
  '--tm-evaluation-indicator-editor-border': teacherEvaluationIndicatorEditorSemantic.border,
  '--tm-evaluation-indicator-editor-header-bg': teacherEvaluationIndicatorEditorSemantic.headerBackground,
  '--tm-evaluation-indicator-editor-selected-bg': teacherEvaluationIndicatorEditorSemantic.selectedBackground,
  '--tm-evaluation-indicator-editor-selected-text': teacherEvaluationIndicatorEditorSemantic.selectedText,
  '--tm-evaluation-indicator-editor-focus-ring': teacherEvaluationIndicatorEditorSemantic.focusRing,
  '--tm-evaluation-indicator-editor-active-bg': teacherEvaluationIndicatorEditorSemantic.activeBackground,
  '--tm-chart-percentage-low': teacherReportChartSemantic.percentage.low.fill,
  '--tm-chart-percentage-low-text': teacherReportChartSemantic.percentage.low.text,
  '--tm-chart-percentage-low-soft': teacherReportChartSemantic.percentage.low.soft,
  '--tm-chart-percentage-medium': teacherReportChartSemantic.percentage.medium.fill,
  '--tm-chart-percentage-medium-text': teacherReportChartSemantic.percentage.medium.text,
  '--tm-chart-percentage-medium-soft': teacherReportChartSemantic.percentage.medium.soft,
  '--tm-chart-percentage-high': teacherReportChartSemantic.percentage.high.fill,
  '--tm-chart-percentage-high-text': teacherReportChartSemantic.percentage.high.text,
  '--tm-chart-percentage-high-soft': teacherReportChartSemantic.percentage.high.soft,
  '--tm-chart-positive': teacherReportChartSemantic.positive,
  '--tm-chart-positive-text': teacherReportChartSemantic.positiveText,
  '--tm-chart-positive-soft': teacherReportChartSemantic.positiveSoft,
  '--tm-chart-warning': teacherReportChartSemantic.warning,
  '--tm-chart-warning-text': teacherReportChartSemantic.warningText,
  '--tm-chart-warning-soft': teacherReportChartSemantic.warningSoft,
  '--tm-chart-negative': teacherReportChartSemantic.negative,
  '--tm-chart-negative-text': teacherReportChartSemantic.negativeText,
  '--tm-chart-negative-soft': teacherReportChartSemantic.negativeSoft,
  '--tm-chart-edu-virtue': teacherReportChartSemantic.education.virtue,
  '--tm-chart-edu-wisdom': teacherReportChartSemantic.education.wisdom,
  '--tm-chart-edu-fitness': teacherReportChartSemantic.education.fitness,
  '--tm-chart-edu-aesthetic': teacherReportChartSemantic.education.aesthetic,
  '--tm-chart-edu-labor': teacherReportChartSemantic.education.labor,
  '--tm-chart-indicator-1': teacherReportChartSemantic.indicators[0],
  '--tm-chart-indicator-2': teacherReportChartSemantic.indicators[1],
  '--tm-chart-indicator-3': teacherReportChartSemantic.indicators[2],
  '--tm-chart-indicator-4': teacherReportChartSemantic.indicators[3],
  '--tm-chart-indicator-5': teacherReportChartSemantic.indicators[4],
  '--tm-chart-indicator-6': teacherReportChartSemantic.indicators[5],
  '--tm-chart-grid': teacherReportChartSemantic.grid,
  '--tm-chart-tooltip': teacherReportChartSemantic.tooltip,
  '--tm-chart-hover': teacherBrandSemantic.chartHover,
  // 对比系列：历史数据降低透明度，外部参照使用蓝灰，次级汇总使用深蓝灰。
  '--tm-chart-series-muted-opacity': '0.4',
  '--tm-chart-series-peer': teacherReportChartSemantic.peer,
  '--tm-chart-series-total': teacherReportChartSemantic.total,
  '--tm-focus-ring': teacherBrandSemantic.primary,
  '--tm-input-focus-ring': 'transparent',
  '--tm-mask': teacherBrandSemantic.mask,
  '--tm-shadow-brand-color': 'rgba(224, 39, 39, 0.30)',
  '--tm-shadow-neutral-color': 'rgba(64, 60, 58, 0.18)',
  '--tm-shadow-card': '0 12px 28px -20px rgba(64, 60, 58, 0.12)',
  '--tm-shadow-card-raised': '0 14px 32px -20px rgba(64, 60, 58, 0.16)',
  '--tm-shadow-card-on-white': '0 1px 4px rgba(64, 60, 58, 0.10), 0 12px 28px -14px rgba(64, 60, 58, 0.16)',
  '--tm-shadow-card-ambient': '0 1px 3px rgba(64, 60, 58, 0.04), 0 8px 20px -14px rgba(64, 60, 58, 0.08)',
  '--tm-shadow-control': '0 6px 16px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-icon': '0 10px 22px -16px rgba(224, 39, 39, 0.24)',
  '--tm-shadow-avatar': '0 18px 28px -18px rgba(224, 39, 39, 0.24)',
  '--tm-shadow-floating': '0 -10px 24px -12px rgba(64, 60, 58, 0.18), 0 10px 28px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-floating-raised': '0 14px 32px -12px var(--tm-shadow-brand-color), 0 8px 20px -10px var(--tm-shadow-neutral-color)',
  '--tm-floating-image-button-shadow': '0 3px 10px rgba(64, 60, 58, 0.20), 0 14px 26px -8px rgba(28, 128, 118, 0.28)',
  '--tm-shadow-navigation': '0 -6px 18px -14px rgba(64, 60, 58, 0.06)',
  '--tm-shadow-sheet': '0 -20px 52px -34px rgba(64, 60, 58, 0.18)',
  '--tm-glow-primary': 'rgba(224, 39, 39, 0.13)',
  '--tm-glow-secondary': 'rgba(247, 92, 3, 0.11)',
  '--tm-glow-primary-subtle': 'rgba(224, 39, 39, 0.055)',
  '--tm-glow-secondary-subtle': 'rgba(247, 92, 3, 0.05)',
  '--tm-student-detail-profile-bg': 'radial-gradient(circle at 92% 0%, var(--tm-glow-primary-subtle), transparent 46%), radial-gradient(circle at 8% 100%, var(--tm-glow-secondary-subtle), transparent 42%), linear-gradient(var(--tm-bg-surface-glass), var(--tm-bg-surface-glass))',
  '--tm-student-detail-asset-bg': 'rgba(255, 255, 255, 0.24)',
  '--tm-student-detail-asset-border': 'rgba(64, 60, 58, 0.08)',
  '--tm-student-detail-asset-height': '48px',
  '--tm-student-detail-asset-label-width': '80px',
  '--tm-student-detail-asset-chevron-space': 'var(--tm-size-touch)',
  '--tm-role-headteacher-primary': teacherAssistantRoleSemantic.headteacher.primary,
  '--tm-role-headteacher-strong': teacherAssistantRoleSemantic.headteacher.strong,
  '--tm-role-headteacher-soft': teacherAssistantRoleSemantic.headteacher.soft,
  '--tm-role-headteacher-soft-strong': teacherAssistantRoleSemantic.headteacher.softStrong,
  '--tm-role-headteacher-border': teacherAssistantRoleSemantic.headteacher.border,
  '--tm-role-headteacher-highlight': teacherAssistantRoleSemantic.headteacher.highlight,
  '--tm-role-headteacher-glow-primary': teacherAssistantRoleSemantic.headteacher.glowPrimary,
  '--tm-role-headteacher-glow-secondary': teacherAssistantRoleSemantic.headteacher.glowSecondary,
  '--tm-role-headteacher-shadow': teacherAssistantRoleSemantic.headteacher.shadow,
  '--tm-role-headteacher-page-gradient-start': teacherAssistantRoleSemantic.headteacher.pageGradientStart,
  '--tm-role-headteacher-page-gradient-middle': teacherAssistantRoleSemantic.headteacher.pageGradientMiddle,
  '--tm-role-headteacher-page-gradient-end': teacherAssistantRoleSemantic.headteacher.pageGradientEnd,
  '--tm-role-headteacher-glass-surface': teacherAssistantRoleSemantic.headteacher.glassSurface,
  '--tm-role-headteacher-glass-surface-strong': teacherAssistantRoleSemantic.headteacher.glassSurfaceStrong,
  '--tm-role-headteacher-glass-border': teacherAssistantRoleSemantic.headteacher.glassBorder,
  '--tm-role-headteacher-glass-shadow': teacherAssistantRoleSemantic.headteacher.glassShadow,
  '--tm-role-headteacher-context-surface': teacherAssistantRoleSemantic.headteacher.contextSurface,
  '--tm-role-headteacher-data-surface': teacherAssistantRoleSemantic.headteacher.dataSurface,
  '--tm-role-headteacher-context-shadow': teacherAssistantRoleSemantic.headteacher.contextShadow,
  '--tm-role-headteacher-data-shadow': teacherAssistantRoleSemantic.headteacher.dataShadow,
  '--tm-role-principal-primary': teacherAssistantRoleSemantic.principal.primary,
  '--tm-role-principal-strong': teacherAssistantRoleSemantic.principal.strong,
  '--tm-role-principal-soft': teacherAssistantRoleSemantic.principal.soft,
  '--tm-role-principal-soft-strong': teacherAssistantRoleSemantic.principal.softStrong,
  '--tm-role-principal-border': teacherAssistantRoleSemantic.principal.border,
  '--tm-role-principal-accent': teacherAssistantRoleSemantic.principal.accent,
  '--tm-role-principal-accent-strong': teacherAssistantRoleSemantic.principal.accentStrong,
  '--tm-role-principal-highlight': teacherAssistantRoleSemantic.principal.highlight,
  '--tm-role-principal-accent-soft': teacherAssistantRoleSemantic.principal.accentSoft,
  '--tm-role-principal-accent-border': teacherAssistantRoleSemantic.principal.accentBorder,
  '--tm-role-principal-glow-primary': teacherAssistantRoleSemantic.principal.glowPrimary,
  '--tm-role-principal-glow-secondary': teacherAssistantRoleSemantic.principal.glowSecondary,
  '--tm-role-principal-shadow': teacherAssistantRoleSemantic.principal.shadow,
  '--tm-audience-guardian-primary': teacherAudienceSemantic.guardian.primary,
  '--tm-audience-guardian-strong': teacherAudienceSemantic.guardian.strong,
  '--tm-audience-guardian-soft': teacherAudienceSemantic.guardian.soft,
  '--tm-audience-guardian-border': teacherAudienceSemantic.guardian.border,
  '--tm-audience-student-primary': teacherAudienceSemantic.student.primary,
  '--tm-audience-student-strong': teacherAudienceSemantic.student.strong,
  '--tm-audience-student-soft': teacherAudienceSemantic.student.soft,
  '--tm-audience-student-border': teacherAudienceSemantic.student.border,
  '--tm-audience-teacher-primary': teacherAudienceSemantic.teacher.primary,
  '--tm-audience-teacher-strong': teacherAudienceSemantic.teacher.strong,
  '--tm-audience-teacher-soft': teacherAudienceSemantic.teacher.soft,
  '--tm-audience-teacher-border': teacherAudienceSemantic.teacher.border,
  '--tm-radius-control': '12px',
  '--tm-radius-inner': '16px',
  '--tm-radius-card': '20px',
  '--tm-radius-sheet': '28px',
  '--tm-sheet-footer-divider-width': '0px',
  '--tm-size-touch': '44px',
  '--tm-size-floating-action': '52px',
  '--tm-recount-bottom-action-height': '52px',
  '--tm-recount-bottom-action-max-width': '350px',
  '--tm-floating-image-button-width': '68px',
  '--tm-floating-image-button-height': '72px',
  '--tm-floating-image-button-circle-size': '68px',
  '--tm-floating-image-button-image-size': '44px',
  '--tm-floating-image-button-label-width': '64px',
  '--tm-floating-image-button-label-height': '20px',
  '--tm-floating-image-button-border-width': '2px',
  '--tm-floating-image-button-bg': 'var(--tm-bg-surface)',
  '--tm-floating-image-button-border': teacherBrandPalette.gold[300],
  '--tm-floating-image-button-label-bg': teacherBrandPalette.gold[50],
  '--tm-floating-image-button-label-border': teacherBrandPalette.gold[200],
  '--tm-floating-image-button-label-text': teacherBrandPalette.jade[700],
  '--tm-assistant-category-pill-width': '108px',
  '--tm-assistant-secondary-pill-height': '30px',
  '--tm-assistant-icon-control-visual-size': '36px',
  '--tm-font-size-document-title': '26px',
  '--tm-font-size-page-title': '22px',
  '--tm-font-size-group-title': '18px',
  '--tm-font-size-form-group-label': '14px',
  '--tm-font-size-section-title': '17px',
  '--tm-font-size-card-title': '15px',
  '--tm-font-size-body': '14px',
  '--tm-font-size-compact': '13px',
  '--tm-font-size-meta': '12px',
  '--tm-font-size-badge': '11px',
  '--tm-font-size-metric': '24px',
  '--tm-class-info-title-font-size': '20px',
  '--tm-space-1': '4px',
  '--tm-space-2': '8px',
  '--tm-space-3': '12px',
  '--tm-space-4': '16px',
  '--tm-space-5': '20px',
  '--tm-space-6': '24px',
  '--tm-space-8': '32px',
  '--tm-selection-touch-height': 'var(--tm-size-touch)',
  '--tm-selection-segment-visible-height': '36px',
  '--tm-selection-segment-track-bg': 'var(--tm-bg-surface-muted)',
  '--tm-selection-segment-active-bg': 'var(--tm-bg-surface)',
  '--tm-selection-segment-active-text': 'var(--tm-brand-primary)',
  '--tm-selection-segment-inactive-text': 'var(--tm-text-secondary)',
  '--tm-selection-segment-active-shadow': 'var(--tm-shadow-control)',
  '--tm-selection-text-active': 'var(--tm-brand-primary)',
  '--tm-selection-text-inactive': 'var(--tm-text-secondary)',
  '--tm-selection-pill-visible-height': '32px',
  '--tm-selection-pill-min-width': '60px',
  '--tm-selection-pill-radius': '8px',
  '--tm-selection-pill-active-bg': 'var(--tm-brand-primary)',
  '--tm-selection-pill-active-border': 'var(--tm-brand-primary)',
  '--tm-selection-pill-active-text': 'var(--tm-text-inverse)',
  '--tm-selection-pill-inactive-bg': 'var(--tm-bg-surface)',
  '--tm-selection-pill-inactive-border': 'var(--tm-border-subtle)',
  '--tm-selection-pill-inactive-text': 'var(--tm-text-secondary)',
  '--tm-selection-pill-pressed-bg': 'var(--tm-brand-primary-pressed)',
  '--tm-selection-pill-inactive-pressed-bg': 'var(--tm-bg-surface-soft)',
  '--tm-report-page-inline': 'var(--tm-space-5)',
  '--tm-report-card-gap': 'var(--tm-space-6)',
  '--tm-report-card-padding': 'var(--tm-space-4)',
  '--tm-report-card-content-gap': 'var(--tm-space-4)',
  '--tm-report-coverage-row-height': '48px',
  '--tm-report-coverage-value-height': '24px',
  '--tm-report-coverage-name-inset': 'var(--tm-space-4)',
  '--tm-report-coverage-evaluation-column': '76px',
  '--tm-report-coverage-teacher-column': '104px',
  '--tm-report-filter-padding-top': '0px',
  '--tm-report-filter-padding-bottom': '0px',
  '--tm-report-filter-padding-pinned': '0px',
  '--tm-report-filter-row-height': 'var(--tm-size-touch)',
  '--tm-report-type-font-size': 'var(--tm-font-size-card-title)',
  '--tm-report-period-font-size': 'var(--tm-font-size-compact)',
  '--tm-report-period-pill-height': '28px',
  '--tm-report-period-pill-inline': 'var(--tm-space-2)',
  '--tm-report-scroll-hint-width': '28px',
  '--tm-report-summary-surface': 'var(--tm-bg-surface)',
  '--tm-report-summary-data-surface': 'var(--tm-chart-data-default-soft)',
  '--tm-report-summary-border': 'rgba(74, 114, 176, 0.16)',
  '--tm-report-summary-value-text': 'var(--tm-chart-data-default-text)',
  '--tm-report-summary-compare-text': 'var(--tm-text-secondary)',
  '--tm-report-summary-primary-value-size': '32px',
  '--tm-report-summary-secondary-value-size': '28px',
  '--tm-report-summary-min-height': '128px',
  '--tm-report-summary-padding': 'var(--tm-space-4)',
  '--tm-report-summary-column-gap': 'var(--tm-space-5)',
  '--tm-report-summary-class-row-height': '36px',
  '--tm-report-date-indicator-width': '56px',
  '--tm-report-date-indicator-height': '3px',
  '--tm-report-custom-range-height': '40px',
  '--tm-report-source-list-inline': 'var(--tm-space-2)',
  '--tm-report-source-item-gap': 'var(--tm-space-2)',
  '--tm-report-source-item-inline': '6px',
  '--tm-report-source-padding-top': '0px',
  '--tm-report-source-padding-bottom': '0px',
  '--tm-report-source-pill-height': '28px',
  '--tm-report-source-pill-inline': '6px',
  '--tm-duty-week-grid-gap': 'var(--tm-space-3)',
  '--tm-duty-week-tile-height': '76px',
  '--tm-duty-week-tile-radius': 'var(--tm-radius-inner)',
  '--tm-duty-week-selected-shadow': '0 14px 28px -18px var(--tm-shadow-brand-color)',
  '--tm-duty-week-dimmed-opacity': '0.34',
  '--tm-duty-week-assigned-bg': 'var(--tm-status-positive-soft)',
  '--tm-duty-week-assigned-text': 'var(--tm-status-positive-strong)',
  '--tm-duty-week-unassigned-bg': 'var(--tm-bg-surface-muted)',
  '--tm-duty-week-unassigned-text': 'var(--tm-text-secondary)',
  '--tm-duty-current-button-bg': 'var(--tm-bg-surface)',
  '--tm-duty-current-button-text': 'var(--tm-brand-primary)',
  '--tm-duty-current-button-border': 'var(--tm-brand-primary)',
  '--tm-duty-current-button-shadow': 'none',
  '--tm-duty-current-button-pressed-bg': 'var(--tm-brand-primary-soft)',
  '--tm-duty-unassigned-option-height': '44px',
  '--tm-duty-unassigned-button-visible-height': '28px',
  '--tm-duty-unassigned-button-radius': '8px',
  '--tm-duty-unassigned-button-bg': 'var(--tm-bg-surface)',
  '--tm-duty-unassigned-button-selected-bg': 'var(--tm-brand-primary-soft)',
  '--tm-duty-unassigned-button-pressed-bg': 'var(--tm-brand-primary-soft-strong)',
  '--tm-duty-unassigned-button-border': 'var(--tm-brand-primary)',
  '--tm-duty-unassigned-button-text': 'var(--tm-brand-primary)',
  '--tm-duty-unassigned-button-shadow': 'var(--tm-shadow-control)',
  '--tm-duty-teacher-row-height': '56px',
  '--tm-duration-fast': '150ms',
  '--tm-duration-standard': '200ms',
  '--tm-duration-panel': '300ms',
} satisfies Record<`--${string}`, string>;

export const phoneText = {
  navTitle: 'text-[17px] font-bold leading-tight',
  pageTitle: 'text-[22px] font-bold leading-tight',
  sectionTitle: 'text-[17px] font-semibold leading-snug',
  itemTitle: 'text-[15px] font-normal leading-snug',
  body: 'text-[14px] font-medium leading-relaxed',
  helper: 'text-[12px] font-normal leading-snug',
  label: 'text-[11px] font-bold leading-none',
  metric: 'text-[24px] font-bold leading-none',
} as const;

export const phoneRadius = {
  sm: 'rounded-[8px]',
  md: 'rounded-[12px]',
  lg: 'rounded-[16px]',
  xl: 'rounded-[20px]',
  sheet: 'rounded-[28px]',
  full: 'rounded-full',
} as const;

export const phoneShadow = {
  none: 'shadow-none',
  card: '[box-shadow:var(--tm-shadow-card)]',
  raised: '[box-shadow:var(--tm-shadow-card-raised)]',
  onWhite: '[box-shadow:var(--tm-shadow-card-on-white)]',
  ambient: '[box-shadow:var(--tm-shadow-card-ambient)]',
  floating: '[box-shadow:var(--tm-shadow-floating)]',
  floatingRaised: '[box-shadow:var(--tm-shadow-floating-raised)]',
  modal: '[box-shadow:var(--tm-shadow-sheet)]',
} as const;

export const phoneSpace = {
  pageX: 'px-5',
  sectionGap: 'space-y-5',
  cardMd: 'p-4',
  cardLg: 'p-6',
} as const;

export const phoneTone = {
  brand: {
    box: 'border-[var(--tm-brand-primary-soft-strong)] bg-[var(--tm-brand-primary-soft)] text-[var(--tm-brand-primary)]',
    soft: 'border-[var(--tm-brand-primary-soft-strong)] bg-[var(--tm-brand-primary-soft)] text-[var(--tm-brand-primary-pressed)]',
  },
  secondary: {
    box: 'border-[var(--tm-brand-secondary)]/20 bg-[var(--tm-brand-secondary-soft)] text-[var(--tm-brand-secondary-strong)]',
    soft: 'border-[var(--tm-brand-secondary)]/20 bg-[var(--tm-brand-secondary-soft)] text-[var(--tm-brand-secondary-strong)]',
  },
  reward: {
    box: 'border-[var(--tm-brand-reward)]/20 bg-[var(--tm-brand-reward-soft)] text-[var(--tm-brand-reward-strong)]',
    soft: 'border-[var(--tm-brand-reward)]/20 bg-[var(--tm-brand-reward-soft)] text-[var(--tm-brand-reward-strong)]',
  },
  positive: {
    box: 'border-[var(--tm-status-positive)]/20 bg-[var(--tm-status-positive-soft)] text-[var(--tm-status-positive-strong)]',
    soft: 'border-[var(--tm-status-positive)]/20 bg-[var(--tm-status-positive-soft)] text-[var(--tm-status-positive-strong)]',
  },
  negative: {
    box: 'border-[var(--tm-status-negative)]/20 bg-[var(--tm-status-negative-soft)] text-[var(--tm-status-negative-strong)]',
    soft: 'border-[var(--tm-status-negative)]/20 bg-[var(--tm-status-negative-soft)] text-[var(--tm-status-negative-strong)]',
  },
  neutral: {
    box: 'border-[var(--tm-border-subtle)] bg-[var(--tm-bg-surface-soft)] text-[var(--tm-text-secondary)]',
    soft: 'border-[var(--tm-border-subtle)] bg-[var(--tm-bg-surface-soft)] text-[var(--tm-text-secondary)]',
  },
} as const;

export type PhoneTone = keyof typeof phoneTone;
