import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./SmartBigScreen.tsx', import.meta.url), 'utf8');
const performanceSource = readFileSync(new URL('./classroom/ClassroomPerformanceValues.tsx', import.meta.url), 'utf8');

const requireText = (text, message) => assert.ok(source.includes(text), message);

requireText('studentGroupAvatarOptions', 'PC小组卡片与设置应复用手机端的系统头像目录');
requireText('getGroupCardDisplaySettings', 'PC小组卡片应复用统一展示设置');
requireText('createDemoGroupPerformanceSummary', 'PC小组卡片应接入小组统计摘要');
requireText('groupCountCheckpoints', 'PC小组重新计数应维护独立统计起点');
requireText("const [groupPlans, setGroupPlans] = useState<GroupPlan[]>", '分组方案应为可编辑状态，不应继续使用只读派生数据');
requireText('isActiveGroupPlanOwnedByCurrentTeacher', '分组管理能力应受方案创建人权限约束');
requireText('新建另一套分组', '方案菜单应支持创建新方案');
requireText('分组方案名称', '新方案应先填写方案名称');
requireText('第一个小组名称', '新方案应同时定义第一个小组名称');
requireText('添加小组', '当前教师自己的方案应支持继续添加小组');
requireText("type GroupDrawerMode = 'view' | 'adjust' | 'settings' | 'create-members'", '小组详情、成员调整和设置应在同一抽屉流程中渐进披露');
requireText('调整学生', '小组详情应支持调整成员');
requireText('仅看未分组', '成员调整应支持只查看未分组学生');
requireText('小组头像', '小组设置应支持选择正式头像');
requireText('confirmDissolveGroup', '小组详情应提供受权限保护的解散能力');
requireText("viewMode === 'group' ? '小组卡片展示' : '学生卡片展示'", '更多操作必须按当前视图区分学生和小组展示设置');
requireText("startRecountSelection(viewMode)", '更多操作中的重新计数必须作用于当前视图对象');
requireText('updateGroupPerformance(targetGroupIds, scoreChange)', '小组评价应更新小组自身统计');
requireText("updateGroupPerformance(record.groupIds ?? [], record.scoreChange, 'revert')", '撤销小组评价时应同步恢复小组统计');
requireText('groupIds: [matchedGroup.id]', '语音识别到小组时应保留小组目标');
requireText('updateGroupPerformance(targets.groupIds ?? [], scoreChange)', '语音小组评价应更新小组统计');
requireText("[nextGroup.id]: { netScore: 0, praiseCount: 0, criticismCount: 0, praiseScore: 0, criticismScore: 0 }", '新建小组统计必须从零开始');
requireText('getClassroomDisplayConfig', '小组相关侧栏应读取统一课堂展示配置');
requireText('const groupDrawerWidth = `min(${classroomDisplay.groupDrawerWidth}px, calc(100vw - 32px))`', '小组抽屉必须根据展示档位适配窄视口');
requireText('width={groupDrawerWidth}', '小组抽屉必须使用统一侧栏宽度');
requireText('zIndex={10010}', '小组抽屉应高于演示环境切换器，避免右侧控件侵入内容');
requireText('组内学生', '小组详情应使用明确的成员区标题承载调整入口');
requireText('gridTemplateColumns: `repeat(auto-fill, ${classroomDisplay.studentCard.width}px)`', '小组成员卡片应读取当前档位的学生卡片宽度');
requireText('groupPlanActionMenuWidth', '方案管理操作菜单宽度应根据展示档位适配');
requireText("top: `calc(100% + 4px)`", '方案管理操作应使用局部浮层，不得撑高方案列表项');
requireText('height: classroomDisplay.groupCard.fullHeight', '添加小组入口必须与当前尺寸的小组卡片等高');
requireText('bodyStyle={{ padding: 0 }}', '所有小组抽屉模式必须复用同一内容内边距规则');
requireText('const GroupDrawerBody', '小组详情、新增、调整与设置应复用统一抽屉内容容器');
requireText('groupEditorStudentSections', '关闭仅看未分组后，学生选择结果必须按现有小组组织');
requireText('GroupMemberSelectCard', '添加小组应使用统一的头像、学号与姓名选择卡片');
requireText('<ClassroomRosterBadge studentNo={student.studentNo} fontSize={layout.studentNoFontSize} lineHeight={16} variant="select" ariaHidden />', '分组选人卡片应复用统一两位编号组件');
requireText('gridTemplateColumns: `repeat(auto-fill, minmax(${classroomDisplay.memberSelect.columnMinWidth}px, 1fr))`', 'PC抽屉内学生卡片应根据档位保持稳定列宽');
requireText('line-clamp-2 min-w-0 font-bold leading-5 text-slate-500', '小组卡片成员姓名应使用两行摘要，提升成员可见数量');
requireText('layout.memberFontSize', '小组卡片成员字号应随课堂展示档位调整');
requireText('const visibleNameCount = 4', 'PC小组卡片应最多展示四个成员姓名');
requireText('ClassroomPerformanceValues', '小组评价统计应复用PC课堂大屏公共组件');
requireText('ariaLabelPrefix="小组"', '小组评价统计应保留明确的读屏语义');
requireText('orientation="vertical"', '小组评价统计应在卡片右侧纵向排列，释放成员信息宽度');
requireText("${viewMode === 'group' ? 'grid justify-start' : 'grid justify-center'} gap-3 pb-20 relative", '小组卡片应使用左对齐网格，从左到右、从上到下排列，学生卡片保留原有居中策略');
requireText('gridTemplateColumns: `repeat(auto-fill, ${viewMode === \'group\' ? classroomDisplay.groupCard.width : classroomDisplay.studentCard.width}px)`', '课堂卡片网格应使用当前展示档位的固定列宽');
requireText('groupCardFlexItemStyle', 'PC小组卡片应共享统一的卡片宽度规则');
assert.doesNotMatch(source, /basis-full flex justify-start/, '添加小组入口不应另起一行，应作为最后一个网格项');
requireText('fontSize: classroomDisplay.toolbar.fontSize', '小组方案筛选的主文案应随课堂展示档位调整字号');
requireText('classroomDisplay.toolbar.groupPlanMetaFontSize', '小组方案筛选的辅助文案应随课堂展示档位调整字号');
assert.doesNotMatch(source, /groupCardSpan|col-span-2/, '小组卡片不应继续通过跨两列制造宽卡片');
requireText('等${group.memberCount}名学生', '超过四个成员时应使用等人数文案');
requireText('，共${group.memberCount}名学生', '不超过四个成员时应使用共人数文案');
requireText('const groupMoveNotice = useMemo', '跨组选择提醒应由当前选择状态实时汇总');
requireText('已选：${nameSummary}', '跨组选择提醒应展示已选学生摘要');
assert.doesNotMatch(source, /const toggleGroupDraftMember[\s\S]{0,500}setToastMsg/, '跨组选择提醒不应使用短时全局 toast 定时消失');
assert.ok(performanceSource.includes('bg-emerald-50') && performanceSource.includes('text-emerald-700'), 'PC公共组件应统一加分色块与高对比度文字');
assert.ok(performanceSource.includes('bg-rose-50') && performanceSource.includes('text-rose-700'), 'PC公共组件应统一扣分色块与高对比度文字');
requireText('z-[10030]', '全局提示必须高于抽屉和弹窗层级');
requireText('role="status" aria-live="polite"', '抽屉内学生移动提示应使用可感知的状态语义');
requireText('MobileEmptyState', '学生选择为空时应复用现有缺省状态组件');
requireText('ASSETS.DEFAULT_STATE.MAGNIFIER', '搜索无结果时应使用现有放大镜缺省图片');
requireText('ASSETS.DEFAULT_STATE.CHAIR', '无可选学生时应使用现有座椅缺省图片');

assert.doesNotMatch(source, /const groupPlans = useMemo\(\(\) => GENERATE_MOCK_GROUP_PLANS/, '分组方案不得继续在渲染层按只读数据生成');
assert.doesNotMatch(source, /bg-gradient-to-br from-indigo-500 to-purple-600[\s\S]{0,180}group\.name\.slice/, '小组卡片不得继续使用首字渐变占位头像');
assert.doesNotMatch(source, /flex items-center justify-end gap-1 border-t border-slate-100 bg-slate-50/, '方案管理操作不得展开为额外列表行');

console.log('SmartBigScreen grouping assertions passed');
