import assert from 'node:assert/strict';
import fs from 'node:fs';

const dashboard = fs.readFileSync('components/TeacherDashboard.tsx', 'utf8');

assert.match(dashboard, /campaignsAudienceOverlap\(item, campaignForm\)/, '冲突广告必须按投放对象筛选。');
assert.match(dashboard, /同投放对象、同时段存在/, '冲突提示应说明投放对象和时间共同重叠。');
assert.match(dashboard, /投放版本/, '冲突详情应展示投放版本。');
assert.match(dashboard, /展示频率/, '冲突详情应展示展示频率。');
assert.match(dashboard, /达到展示频率后自动展示下一个广告/, '冲突提示应说明广告达到频率后会继续展示下一条。');
assert.match(dashboard, /老师下次进入时可继续看到其他广告/, '仅一次广告应说明老师后续仍能看到其他广告。');
assert.match(dashboard, /广告状态筛选/, '广告列表应提供状态筛选。');
assert.match(dashboard, /campaign\.publishStatus === 'online'/, '活动列表应使用上架状态展示和筛选。');
assert.match(dashboard, /toggleCampaignPublishStatus/, '活动列表应支持上架和下架操作。');
assert.match(dashboard, /暂无符合条件的广告/, '状态筛选无结果时应展示空状态。');
assert.match(dashboard, /placeholder="搜索广告名称"/, '广告列表应提供独立的名称搜索。');
assert.match(dashboard, /aria-label="广告列表筛选"/, '名称搜索和状态筛选应位于独立筛选栏。');
assert.match(dashboard, /<Input value=\{campaignForm\.name\}/, '广告名称应使用 Arco 输入框。');
assert.match(dashboard, /<InputNumber min=\{0\} max=\{99\}/, '优先级应使用 Arco 数字输入框。');
assert.match(dashboard, /className="pc-form overflow-y-auto p-6"/, '广告配置表单应使用独立的可编辑态样式容器。');
assert.doesNotMatch(dashboard, /活动类型/, '广告表单不应继续展示活动类型字段。');
assert.match(dashboard, /建议尺寸 750 × 1000 px（3:4 竖版）/, '活动素材应提示建议上传尺寸。');
assert.match(dashboard, /children: \['广告投放'\]/, '运营中心菜单应改名为广告投放。');
assert.match(dashboard, /应用内弹窗/, '广告投放位应使用应用内弹窗文案。');
assert.match(dashboard, /启动页/, '广告投放位应保留启动页文案。');
assert.match(dashboard, /<Radio value="all">全部<\/Radio>/, '投放范围应支持全部版本。');
assert.match(dashboard, /未付费个人/, '个人版投放应支持未付费个人范围。');
assert.match(dashboard, /指定学校/, '学校版投放应支持指定学校范围。');
assert.match(dashboard, /指定角色/, '学校版投放应支持指定角色范围。');
assert.match(dashboard, /每周一次/, '展示频率应支持每周一次。');
assert.match(dashboard, /全部页面/, '应用内弹窗应支持全部页面。');
assert.match(dashboard, /指定页面/, '应用内弹窗应支持指定页面。');
assert.doesNotMatch(dashboard, /展示频率<select/, '展示频率不应继续使用原生选择器。');
assert.doesNotMatch(dashboard, /\{campaignStatusLabels\[status\]\}<\/div>/, '活动列表状态列不应展示投放中等时间状态文案。');
assert.match(dashboard, /campaignPrioritySort/, '活动列表应维护优先级排序状态。');
assert.match(dashboard, /aria-sort=\{campaignPrioritySort/, '优先级表头应暴露当前排序状态。');
assert.match(dashboard, /b\.priority - a\.priority/, '优先级应支持从高到低排序。');
assert.match(dashboard, /a\.priority - b\.priority/, '优先级应支持从低到高排序。');

console.log('活动冲突提示断言通过');
