export const questionnaireThemePalette = {
  red: {
    50: '#FFF1F1',
    100: '#FFE2E2',
    200: '#FFC7C7',
    500: '#E02727',
    600: '#CC2020',
    700: '#BA352E',
  },
  neutral: {
    0: '#FFFFFF',
    50: '#F8F6F5',
    100: '#F1EEEC',
    200: '#E7E2DF',
    400: '#A49C97',
    450: '#918985',
    500: '#6D6764',
    550: '#7B7572',
    900: '#171513',
  },
  green: {
    50: '#F4FBF4',
    500: '#48A04D',
    700: '#2E7D32',
  },
} as const;

export const questionnaireThemeCssVariables = {
  '--tm-brand-primary': questionnaireThemePalette.red[500],
  '--tm-brand-primary-strong': questionnaireThemePalette.red[700],
  '--tm-brand-primary-pressed': questionnaireThemePalette.red[700],
  '--tm-brand-primary-soft': questionnaireThemePalette.red[50],
  '--tm-brand-primary-soft-strong': questionnaireThemePalette.red[100],
  '--tm-status-positive': questionnaireThemePalette.green[500],
  '--tm-status-positive-strong': questionnaireThemePalette.green[700],
  '--tm-status-positive-soft': questionnaireThemePalette.green[50],
  '--tm-status-negative': questionnaireThemePalette.red[500],
  '--tm-status-negative-strong': questionnaireThemePalette.red[700],
  '--tm-status-negative-soft': questionnaireThemePalette.red[50],
  '--tm-bg-page': questionnaireThemePalette.neutral[50],
  '--tm-bg-surface': questionnaireThemePalette.neutral[0],
  '--tm-bg-surface-soft': questionnaireThemePalette.neutral[50],
  '--tm-bg-surface-muted': questionnaireThemePalette.neutral[100],
  '--tm-bg-page-glass': 'rgba(255, 249, 246, 0.92)',
  '--tm-bg-surface-glass': 'rgba(255, 255, 255, 0.92)',
  '--tm-text-primary': questionnaireThemePalette.neutral[900],
  '--tm-text-secondary': questionnaireThemePalette.neutral[500],
  '--tm-text-tertiary': questionnaireThemePalette.neutral[550],
  '--tm-text-disabled': questionnaireThemePalette.neutral[400],
  '--tm-text-inverse': questionnaireThemePalette.neutral[0],
  '--tm-border-subtle': questionnaireThemePalette.neutral[200],
  '--tm-border-control': questionnaireThemePalette.neutral[450],
  '--tm-questionnaire-progress': questionnaireThemePalette.neutral[900],
  '--tm-input-focus-ring': 'rgba(224, 39, 39, 0.16)',
  '--tm-mask': 'rgba(23, 21, 19, 0.42)',
  '--tm-shadow-card': '0 10px 28px -20px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-control': '0 6px 16px -12px rgba(64, 60, 58, 0.18)',
  '--tm-shadow-sheet': '0 -20px 52px -34px rgba(64, 60, 58, 0.18)',
  '--tm-radius-control': '12px',
  '--tm-radius-inner': '16px',
  '--tm-radius-card': '20px',
  '--tm-radius-sheet': '28px',
  '--tm-size-touch': '44px',
  '--tm-font-size-page-title': '22px',
  '--tm-font-size-document-title': '22px',
  '--tm-font-size-group-title': '18px',
  '--tm-font-size-form-group-label': '14px',
  '--tm-font-size-question-title': '16px',
  '--tm-font-size-control': '14px',
  '--tm-font-size-section-title': '17px',
  '--tm-font-size-card-title': '15px',
  '--tm-font-size-body': '14px',
  '--tm-font-size-compact': '13px',
  '--tm-font-size-meta': '12px',
  '--tm-font-size-badge': '11px',
  '--tm-duration-fast': '150ms',
  '--tm-duration-panel': '300ms',
} satisfies Record<`--${string}`, string>;
