import assert from 'node:assert/strict';
import fs from 'node:fs';

const settingsSource = fs.readFileSync(new URL('./ParentEvaluationVisibilitySettings.tsx', import.meta.url), 'utf8');
const classListSource = fs.readFileSync(new URL('../../views/ClassListView.tsx', import.meta.url), 'utf8');

assert.ok(classListSource.includes("label: '家长端展示'"), '班级更多操作应包含家长端展示入口。');
assert.ok(classListSource.includes('canConfigureParentEvaluationVisibility'), '入口应使用统一班级权限规则。');
assert.match(classListSource, /<MobileBottomSheet[\s\S]*title="家长端评价展示"[\s\S]*<ParentEvaluationVisibilitySettings/, '家长端展示应在单个底部弹窗内直接配置。');
assert.match(classListSource, /title="家长端评价展示"[\s\S]*size="content"/, '配置与预览应使用内容自适应弹窗。');
assert.ok(settingsSource.includes('表扬'), '弹窗应直接展示表扬设置。');
assert.ok(settingsSource.includes('待改进'), '弹窗应直接展示待改进设置。');
assert.ok(settingsSource.includes("{ value: 'hidden', label: '不展示' }"), '应提供不展示选项。');
assert.ok(settingsSource.includes("{ value: 'summary', label: '仅统计' }"), '应提供仅统计选项。');
assert.ok(settingsSource.includes("{ value: 'summaryAndDetails', label: '统计和明细' }"), '应提供统计和明细选项。');
assert.equal((settingsSource.match(/<CompactSegmentedControl/g) ?? []).length, 2, '正负向选项应在同一弹窗直接展示。');
assert.equal((settingsSource.match(/fullWidth/g) ?? []).length, 2, '家长端评价展示的两组切换必须保持内容区全宽。');
assert.doesNotMatch(settingsSource, /variant="settings"/, '学生卡片设置项的固定宽度规格不得影响家长端评价展示。');
assert.ok(!settingsSource.includes('classDisplayName'), '弹窗不应显示具体班级名称。');
assert.ok(!settingsSource.includes('MobileBottomSheet'), '配置内容不应再嵌套弹窗。');
assert.ok(!settingsSource.includes('已保存'), '配置后不应显示已保存提示。');
assert.ok(settingsSource.includes('>家长将看到</h3>'), '弹窗应直接说明下方是家长可见结果。');
assert.ok(settingsSource.includes('bg-[var(--tm-chart-positive)]') && settingsSource.includes('bg-[var(--tm-chart-negative)]'), '表扬与待改进配置应使用语义标记建立上下映射。');
assert.doesNotMatch(settingsSource, /正向评价|负向评价/, '配置弹窗不应继续展示系统化的正负向分类文案。');
assert.match(settingsSource, /<h3[^>]*>家长将看到<\/h3>/, '结果区应使用独立板块标题。');
assert.ok(settingsSource.includes('-mx-[var(--tm-space-4)]') && settingsSource.includes('border-y') && settingsSource.includes('bg-[var(--tm-bg-surface-soft)]'), '结果区应使用通栏浅色表面与配置区分层。');
assert.ok(settingsSource.includes('mt-[var(--tm-space-6)]'), '结果区应与配置区保持24像素间距。');
assert.ok(settingsSource.includes('-mb-[calc(var(--tm-space-4)+env(safe-area-inset-bottom))]') && settingsSource.includes('pb-[calc(var(--tm-space-4)+var(--tm-space-4)+env(safe-area-inset-bottom))]'), '结果区浅色表面应延伸覆盖弹窗底部安全区。');
assert.ok(!settingsSource.includes('rounded-[var(--tm-radius-inner)] bg-[var(--tm-bg-surface-soft)] p-[var(--tm-space-3)]'), '结果区不应继续使用浅色圆角外层容器包裹白色卡片。');
assert.doesNotMatch(settingsSource, />成长数据<|>本周统计<|>评价明细<\/h4>/, '预览不应显示成长数据、本周统计和评价明细等冗余标题。');
assert.ok(settingsSource.includes('总分'), '总分应始终出现在预览中。');
assert.match(settingsSource, />2<span[^>]*>分<\/span>/, '预览总分应与一条加3分和一条减1分案例一致。');
assert.equal((settingsSource.match(/>1<span[^>]*>次<\/span>/g) ?? []).length, 2, '预览应显示表扬1次、待改进1次。');
assert.ok(settingsSource.includes("visibility.positive !== 'hidden'") && settingsSource.includes("visibility.negative !== 'hidden'"), '正负向统计应分别受配置控制。');
assert.ok(settingsSource.includes("visibility.positive === 'summaryAndDetails'") && settingsSource.includes("visibility.negative === 'summaryAndDetails'"), '正负向明细应分别只在统计和明细方案下显示。');
assert.ok(settingsSource.includes('aria-label="评价明细预览"'), '预览明细移除可见标题后仍应保留无障碍语义。');
assert.ok(settingsSource.includes('张三老师') && settingsSource.includes('李敏老师'), '示例评价人应使用姓名加老师的家长端文案。');
assert.ok(settingsSource.includes('你在课堂上主动分享自己创造性的解题思路，帮助其他同学成长。') && settingsSource.includes("score: '+3分'"), '正向案例应使用确认后的评价文案和得分。');
assert.ok(settingsSource.includes('你在课间追逐打闹，经提醒后及时改正。') && settingsSource.includes("score: '-1分'"), '负向案例应使用确认后的评价文案和得分。');
assert.ok(!settingsSource.includes('德育'), '预览明细不应显示评价指标名称。');

console.log('Parent evaluation visibility settings assertions passed');
